const $=id=>document.getElementById(id);let config={};try{config=JSON.parse(decodeURIComponent(location.hash.replace(/^#orbit-config=/,'')))}catch{}
$('current').textContent=typeof config.task==='string'?config.task:'No task snapshot set';$('detail').textContent=typeof config.detail==='string'?config.detail:'Ask Hermes to update this card when starting a workspace change.';
const stages=['Queued','In progress','Blocked','Done'];const labels=['Code changed','Tests passed','Desktop acknowledged','Appearance checked'];let tasks=[],active=null,dirty=false;
const notice=s=>$('notice').textContent=s;
function changed(){dirty=true;notice('Unsaved session changes — export to keep a copy.')}
function button(text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=fn;return b}
function render(){ $('queue').replaceChildren();$('count').textContent=tasks.length+' tasks';if(!tasks.length){const p=document.createElement('p');p.className='muted';p.textContent='Your queue is empty. Add your next idea above.';$('queue').append(p)}
for(const t of tasks){const a=document.createElement('article'),p=document.createElement('p'),row=document.createElement('div'),s=document.createElement('select');row.className='row';p.textContent=t.title;s.setAttribute('aria-label','Status for '+t.title);for(const status of stages){const o=document.createElement('option');o.textContent=status;o.selected=t.status===status;s.append(o)}s.onchange=()=>{t.status=s.value;changed()};row.append(s,button(t.id===active?'Selected':'Inspect',()=>{active=t.id;render()}),button('Remove',()=>{tasks=tasks.filter(x=>x!==t);if(active===t.id)active=null;changed();render()}));a.append(p,row);$('queue').append(a)}
const t=tasks.find(x=>x.id===active);$('selected').textContent=t?t.title:'Select a task to record evidence.';$('checks').replaceChildren();$('evidence').disabled=!t;$('fix').disabled=!t;$('evidence').value=t?.evidence||'';
labels.forEach((label,i)=>{const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.disabled=!t;c.checked=!!t?.checks[i];c.onchange=()=>{t.checks[i]=c.checked;changed()};l.append(c,document.createTextNode(' '+label));$('checks').append(l)})}
$('add').onsubmit=e=>{e.preventDefault();const title=$('idea').value.trim();if(!title)return;if(tasks.length>=100)return notice('Maximum 100 tasks. Export and remove old tasks first.');const t={id:crypto.randomUUID(),title,status:'Queued',checks:[false,false,false,false],evidence:''};tasks.push(t);active=t.id;$('idea').value='';changed();render();$('queue').scrollTop=$('queue').scrollHeight};
$('evidence').oninput=()=>{const t=tasks.find(x=>x.id===active);if(t){t.evidence=$('evidence').value;changed()}};
$('fix').onclick=()=>{const t=tasks.find(x=>x.id===active);if(t){t.status='Blocked';t.checks[3]=false;changed();render();notice('Flagged as blocked. Prepare a message to tell Hermes what needs fixing.')}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,tasks},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='workspace-workshop.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);dirty=false;notice('Export requested. Keep the downloaded JSON to restore this board.')};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>600000)throw Error('File is too large.');const data=JSON.parse(await f.text());if(data.version!==1||!Array.isArray(data.tasks)||data.tasks.length>100)throw Error('Invalid board format.');const incoming=data.tasks.map(t=>{if(typeof t.title!=='string'||!t.title.trim()||t.title.length>240||!stages.includes(t.status)||!Array.isArray(t.checks)||t.checks.length!==4||t.checks.some(c=>typeof c!=='boolean')||typeof t.evidence!=='string'||t.evidence.length>4000)throw Error('Invalid task.');return {...t,id:crypto.randomUUID()}});if(tasks.length+incoming.length>100)throw Error('Import would exceed 100 tasks.');tasks.push(...incoming);active=incoming[0]?.id||active;changed();render();notice('Imported '+incoming.length+' tasks (merged; existing tasks kept).')}catch(e){notice('Import failed: '+e.message)}finally{$('file').value=''}};
$('handoff').onclick=()=>{const selected=tasks.find(t=>t.id===active);const list=selected?[selected]:tasks;$('message').hidden=false;$('message').value='Workspace Workshop request (manually recorded):\n'+list.map(t=>`${t.title}\nStatus: ${t.status}\nRecorded checks: ${labels.filter((_,i)=>t.checks[i]).join(', ')||'None'}\nNotes: ${t.evidence||'None'}`).join('\n\n');$('message').focus();$('message').select();notice('Copy the selected text and paste it into our chat.')};render();
