import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {robotModel,weaponModel,vehicleModel} from '../cocs-viewer/vendor/game/view.mjs';
import {characterPose} from '../cocs-viewer/vendor/game/character-anim.mjs';
import {CHARACTERS,POWERUPS} from '../cocs-viewer/vendor/game/data.mjs';
import {ranges,defaults,presets,validateRecipe,variation,vertexShader,fragmentShader,brief} from './recipe.mjs';
const $=id=>document.getElementById(id),base='https://kimi.tailec998.ts.net:10447';
const state=window.graphicsLab={ready:false,frames:0,bots:[],errors:[],recipe:{...defaults},source:SOURCE_COMMIT};
let recipe={...defaults},draft=null,loadedDigest='',sending=false,renderer,camera,controls,composer,bloom,grade,scene,light,fill,ambient,last=performance.now(),effectTime=0,variationSeed=7100;
const keys=new Set(),originTarget=new T.Vector3(0,1,0);
const download=(name,text,type='application/json')=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);};
function report(e){$('status').textContent=e.message||String(e);$('review').hidden=false;}
async function api(op,data={}){const r=await fetch(base+(op==='recipes'||op==='saveRecipe'?'/recipes':'/api'),{method:'POST',headers:{'Content-Type':'application/json','X-Workshop-Token':window.graphicsToken},body:JSON.stringify({op,...data}),credentials:'omit'});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
function context(){for(const id of ['duration','fadeIn','fadeOut'])if(!$(id).checkValidity())throw Error('Invalid '+id);return {situation:$('situation').value,trigger:$('trigger').value,duration:+$('duration').value,fadeIn:+$('fadeIn').value,fadeOut:+$('fadeOut').value,prompt:$('prompt').value,scene:$('scene').value};}
function changeBrief(){return brief(recipe,context());}
function apply(r){recipe=validateRecipe(r);state.recipe={...recipe};for(const k of Object.keys(ranges)){const input=$(k);input.value=recipe[k];$('val-'+k).value=Number(recipe[k]).toFixed(k==='chromatic'?4:2);} $('tint').value=recipe.tint;if(camera){camera.fov=recipe.fov;camera.updateProjectionMatrix();}}
for(const [k,[lo,hi]] of Object.entries(ranges)){const label=document.createElement('label');label.textContent=k.replace(/([A-Z])/g,' $1');const output=document.createElement('output');output.id='val-'+k;const input=document.createElement('input');input.type='range';input.id=k;input.min=lo;input.max=hi;input.step=k==='chromatic'?.0001:k==='pixelSize'||k==='fov'?1:.01;input.value=defaults[k];input.oninput=()=>apply({...recipe,[k]:+input.value});label.append(output,input);$('sliders').append(label);}
for(const name of Object.keys(presets))$('preset').add(new Option(name,name));
$('preset').onchange=()=>apply({...defaults,...presets[$('preset').value]});$('reset').onclick=()=>{$('preset').value='Neutral';apply(defaults);};$('tint').oninput=()=>apply({...recipe,tint:$('tint').value});
$('variants').onclick=()=>{const source={...recipe};$('candidates').replaceChildren();for(let i=0;i<4;i++){const r=variation(source,++variationSeed),b=document.createElement('button');b.textContent='Variation '+variationSeed;b.title=JSON.stringify(r);b.onclick=()=>{apply(r);for(const el of $('candidates').children)el.classList.toggle('selected',el===b);};$('candidates').append(b);}};
for(const p of POWERUPS)$('trigger').add(new Option(p.name+' · '+p.id,'powerup:'+p.id));$('trigger').add(new Option('Custom situation (describe below)','custom'));
$('trigger').onchange=()=>{const p=POWERUPS.find(x=>'powerup:'+x.id===$('trigger').value);if(p?.duration)$('duration').value=p.duration;};$('trigger').onchange();
function documentRecipe(){return {schema:1,name:$('recipeName').value.trim()||'Untitled recipe',source:SOURCE_COMMIT,recipe:{...recipe},context:context(),camera:{position:camera.position.toArray(),target:controls.target.toArray()}};}
function importRecipe(d){if(d.schema!==1)throw Error('Expected Graphics Lab recipe schema 1');const r=validateRecipe(d.recipe);if(d.context){for(const k of ['situation','trigger','duration','fadeIn','fadeOut','prompt','scene'])if(d.context[k]!==undefined&&$(k))$(k).value=String(d.context[k]);}apply(r);$('recipeName').value=String(d.name||'Imported recipe').slice(0,80);setLighting();if(d.camera&&['position','target'].every(k=>Array.isArray(d.camera[k])&&d.camera[k].length===3&&d.camera[k].every(n=>typeof n==='number'&&Number.isFinite(n)&&Math.abs(n)<10000))){camera.position.fromArray(d.camera.position);controls.target.fromArray(d.camera.target);controls.update();}}
$('export').onclick=()=>{try{download('cocs-graphics-recipe.json',JSON.stringify(documentRecipe(),null,2));}catch(e){report(e);}};
$('importButton').onclick=()=>$('import').click();$('import').onchange=async()=>{try{const f=$('import').files[0];if(!f)return;if(f.size>32000)throw Error('Recipe too large');importRecipe(JSON.parse(await f.text()));$('saveStatus').textContent='Imported. Save to retain on host.';}catch(e){report(e);}finally{$('import').value='';}};
let saved=[];async function refreshRecipes(){saved=await api('recipes');$('saved').replaceChildren(new Option('Saved recipes…',''));for(const d of saved)$('saved').add(new Option(d.name,d.id));}
$('save').onclick=async()=>{try{const savedRecipe=await api('saveRecipe',{recipe:documentRecipe()});await refreshRecipes();$('saved').value=savedRecipe.id;$('saveStatus').textContent='Saved privately on host.';}catch(e){report(e);}};
$('saved').onchange=()=>{const d=saved.find(x=>x.id===$('saved').value);if(d)try{importRecipe(d);}catch(e){report(e);}};
$('brief').onclick=()=>{try{$('briefText').value=changeBrief();$('briefText').hidden=false;}catch(e){report(e);}};
$('downloadBrief').onclick=()=>{try{download('cocs-graphics-change-brief.txt',changeBrief(),'text/plain');}catch(e){report(e);}};
$('reviewToggle').onclick=()=>$('review').hidden=!$('review').hidden;
function buttons(){const ready=draft?.status==='ready';$('generate').disabled=sending;$('refine').disabled=sending||!ready;$('preview').disabled=sending||!['ready','published'].includes(draft?.status);$('pr').disabled=sending||!ready||loadedDigest!==draft.digest||!$('approved').checked;$('stop').disabled=!['running','queued','waiting_for_approval'].includes(draft?.status);$('approval').hidden=draft?.status!=='waiting_for_approval';}
function renderDraft(s){draft=s;$('status').textContent=s.status+(s.error?'\n'+s.error:'');$('output').textContent=s.output||'';$('evidence').textContent=(s.files||[]).join('\n')+'\n'+(s.evidence||'');$('diff').textContent=s.diff||'';$('prLink').replaceChildren();if(s.pr&&/^https:\/\/github\.com\/mojomast\/cocs\/pull\/\d+$/.test(s.pr)){const a=document.createElement('a');a.href=s.pr;a.target='_blank';a.rel='noopener';a.textContent='Open pull request';$('prLink').append(a);}buttons();}
async function history(){const items=await api('list');$('history').replaceChildren(new Option('Saved drafts…',''));for(const s of items)$('history').add(new Option(s.status+' · '+s.id.slice(0,6),s.id));}
async function edit(refine){try{const prompt=changeBrief();if(prompt.length>8000)throw Error('Request too long; shorten situation or prompt.');sending=true;loadedDigest='';$('approved').checked=false;$('review').hidden=false;buttons();renderDraft(await api('edit',{asset:'character:'+CHARACTERS[0].id,prompt,...(refine?{id:draft.id}:{})}));await history();}catch(e){report(e);}finally{sending=false;buttons();}}
$('generate').onclick=()=>edit(false);$('refine').onclick=()=>edit(true);
$('history').onchange=async()=>{if(!$('history').value)return;try{loadedDigest='';$('approved').checked=false;renderDraft(await api('get',{id:$('history').value}));}catch(e){report(e);}};
$('preview').onclick=async()=>{try{const d=await api('preview',{id:draft.id});loadedDigest='';$('sourcePreview').srcdoc=d.html;$('sourcePreview').onload=()=>{loadedDigest=d.digest;buttons();};$('previewDialog').showModal();}catch(e){report(e);}};
$('closePreview').onclick=()=>$('previewDialog').close();$('approved').onchange=buttons;
$('pr').onclick=()=>{if($('pr').disabled)return;if(!$('title').value.trim())return report(Error('Enter a PR title.'));$('publishSummary').textContent=$('title').value+'\nFiles: '+draft.files.join(', ')+'\nValidated diff: '+draft.digest;$('confirm').showModal();};$('dismiss').onclick=()=>$('confirm').close();
$('publish').onclick=async()=>{$('confirm').close();sending=true;buttons();try{renderDraft(await api('publish',{id:draft.id,digest:loadedDigest,confirm:true,title:$('title').value}));await history();}catch(e){report(e);}finally{sending=false;buttons();}};
$('stop').onclick=async()=>{try{await api('stop',{id:draft.id});$('status').textContent='Stop requested.';}catch(e){report(e);}};
$('approval').onclick=async()=>{try{const d=await api('approvals',{id:draft.id});$('approvalText').textContent=JSON.stringify(d.approvals||[],null,2);$('toolApproval').showModal();}catch(e){report(e);}};
for(const [id,choice] of [['allow','once'],['deny','deny']])$(id).onclick=async()=>{try{await api('approval',{id:draft.id,choice});$('toolApproval').close();}catch(e){report(e);}};$('closeApproval').onclick=()=>$('toolApproval').close();
setInterval(async()=>{if(!draft||sending||['ready','published','blocked','publish-review'].includes(draft.status))return;try{renderDraft(await api('get',{id:draft.id}));}catch(e){report(e);}},3000);
function box(size,pos,color){const m=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color,metalness:.25,roughness:.6}));m.position.set(...pos);scene.add(m);return m;}
function label(text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#0c1a28dd';ctx.fillRect(0,0,512,96);ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillStyle='#d7f3ff';ctx.fillText(text,256,58);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const s=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:true}));s.position.set(x,y,z);s.scale.set(2.3,.43,1);scene.add(s);}
function setLighting(){if(!scene)return;const night=$('scene').value==='night';scene.background=new T.Color(night?'#050c1b':'#182c40');scene.fog=new T.Fog(scene.background,22,85);ambient.intensity=night?.45:2;light.intensity=night?1:3;fill.intensity=night?3:1;state.scene=$('scene').value;$('sceneTitle').textContent=night?'Night stage / frozen action':'Studio stage / frozen action';}
function overview(){camera.position.set(10,7.5,16);controls.target.copy(originTarget);controls.update();}
function init(){renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.outputColorSpace=T.SRGBColorSpace;scene=new T.Scene();ambient=new T.HemisphereLight('#d9f0ff','#404c59',2);scene.add(ambient);light=new T.DirectionalLight('#ffe5c6',3);light.position.set(8,15,7);scene.add(light);fill=new T.DirectionalLight('#69bfff',1);fill.position.set(-8,6,-7);scene.add(fill);camera=new T.PerspectiveCamera(65,1,.05,200);controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.maxDistance=100;controls.minDistance=.3;overview();
box([65,.2,65],[0,-.15,0],'#344659');const grid=new T.GridHelper(64,32,'#597488','#3d5267');grid.position.y=-.04;scene.add(grid);box([2,1.2,2],[-5,.6,-1.2],'#5d7880');box([2.4,2.6,2],[5,1.3,-3],'#846658');box([18,3,.4],[0,1.5,-9],'#304455');for(let i=0;i<6;i++){const color=new T.Color().setHSL(i/6,.7,.5);box([1.3,1.3,.2],[-5+i*2,1.6,-8.75],color);}
const actions=[['Aiming',{ads:1,focusPitch:.12},[-4,0,1]],['Sprinting',{speedNorm:1,phase:1.1,forward:1},[-1.7,0,-2]],['Airborne',{grounded:false},[1,1.5,-1]],['Reloading',{reload:.8},[3.6,0,1]],['Crouching',{crouch:1,ads:.7},[-2,0,3.7]],['Hit reaction',{hit:1},[1.4,0,4.5]]];
for(let i=0;i<actions.length;i++){const [action,pose,pos]=actions[i],character=CHARACTERS[i%CHARACTERS.length],m=robotModel(character.id);m.position.set(...pos);m.rotation.y=Math.PI+(i%2?.4:-.3);m.userData.rig?.apply(characterPose({...pose,time:2.5}));scene.add(m);const gun=weaponModel(i);gun.scale.setScalar(.8);gun.position.set(.28,1.2,-.4);m.add(gun);label(action,pos[0],pos[1]+2.8,pos[2]);state.bots.push({action,character:character.id,position:[...pos],rig:!!m.userData.rig});$('focus').add(new Option(action+' · '+character.name,String(i)));}
const car=vehicleModel('puma');car.position.set(7,0,-5.5);car.rotation.y=-.6;scene.add(car);label('Puma / material check',7,3,-5.5);const pickup=new T.Mesh(new T.IcosahedronGeometry(.32,1),new T.MeshStandardMaterial({color:'#7cf8ad',emissive:'#62ffb5',emissiveIntensity:3}));pickup.position.set(0,.85,2);scene.add(pickup);const ring=new T.Mesh(new T.TorusGeometry(.55,.035,8,48),new T.MeshBasicMaterial({color:'#6fffba'}));ring.rotation.x=Math.PI/2;ring.position.set(0,.1,2);scene.add(ring);
composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));bloom=new UnrealBloomPass(new T.Vector2(512,512),0,.4,.8);composer.addPass(bloom);composer.addPass(new OutputPass());const uniforms={tDiffuse:{value:null},resolution:{value:new T.Vector2(1,1)},tint:{value:new T.Vector3(1,1,1)},time:{value:0}};for(const k of ['saturation','contrast','tintMix','vignette','chromatic','grain','scanlines','pixelSize','warp'])uniforms[k]={value:defaults[k]};grade=new ShaderPass({uniforms,vertexShader,fragmentShader});composer.addPass(grade);
function resize(){const b=$('viewport').getBoundingClientRect(),w=Math.max(1,b.width),h=Math.max(1,b.height);renderer.setSize(w,h,false);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();grade.uniforms.resolution.value.copy(renderer.getDrawingBufferSize(new T.Vector2()));}new ResizeObserver(resize).observe($('viewport'));resize();setLighting();apply(recipe);$('scene').onchange=setLighting;$('home').onclick=overview;$('eye').onclick=()=>{camera.position.set(0,1.65,8);controls.target.set(0,1.6,-3);controls.update();};$('focus').onchange=()=>{const bot=state.bots[+$('focus').value];if($('focus').value===''||!bot)return;controls.target.set(bot.position[0],bot.position[1]+1.2,bot.position[2]);camera.position.copy(controls.target).add(new T.Vector3(1.8,1,3.4));controls.update();};
$('canvas').onpointerdown=()=>$('viewport').focus();$('viewport').onkeydown=e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();}};window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());$('viewport').onfocusout=()=>keys.clear();
$('shot').onclick=()=>{render(performance.now(),false);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='cocs-graphics-preview.png';a.click();};state.inspect=()=>({camera:camera.position.toArray(),target:controls.target.toArray(),frames:state.frames,bots:state.bots,recipe:state.recipe,scene:state.scene,triangles:renderer.info.render.triangles,canvas:[renderer.domElement.width,renderer.domElement.height]});state.ready=true;requestAnimationFrame(render);}
function draw(r){renderer.toneMappingExposure=r.exposure;bloom.strength=r.bloom;bloom.enabled=r.bloom>.001;for(const k of ['saturation','contrast','tintMix','vignette','chromatic','grain','scanlines','pixelSize','warp'])grade.uniforms[k].value=r[k];const c=r.tint.match(/\w\w/g).map(x=>parseInt(x,16)/255);grade.uniforms.tint.value.set(...c);grade.uniforms.time.value=effectTime;composer.render();}
function render(now,schedule=true){if(schedule)requestAnimationFrame(render);const dt=Math.max(0,Math.min(.05,(now-last)/1000));last=now;if($('motion').checked&&!matchMedia('(prefers-reduced-motion: reduce)').matches)effectTime+=dt;if(keys.size){const f=new T.Vector3();camera.getWorldDirection(f);const right=new T.Vector3().crossVectors(f,camera.up).normalize(),d=new T.Vector3();if(keys.has('KeyW'))d.add(f);if(keys.has('KeyS'))d.sub(f);if(keys.has('KeyA'))d.sub(right);if(keys.has('KeyD'))d.add(right);if(keys.has('KeyQ'))d.y-=1;if(keys.has('KeyE'))d.y+=1;d.multiplyScalar(dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?14:4));camera.position.add(d);controls.target.add(d);}controls.update();draw($('bypass').checked?defaults:recipe);if($('split').checked&&!$('bypass').checked){renderer.setScissorTest(true);const size=renderer.getSize(new T.Vector2());renderer.setScissor(0,0,Math.floor(size.x/2),size.y);renderer.toneMappingExposure=defaults.exposure;renderer.render(scene,camera);renderer.setScissorTest(false);}$('compareLabel').hidden=!$('split').checked||$('bypass').checked;state.frames++;if(state.frames%30===0)$('stats').textContent=`6 FROZEN BOTS · ${renderer.info.render.triangles.toLocaleString()} triangles (last pass) · ${renderer.domElement.width} × ${renderer.domElement.height} · ${$('bypass').checked?'BASELINE':'RECIPE'} · source ${SOURCE_COMMIT.slice(0,8)}`;}
window.addEventListener('error',e=>{state.errors.push(e.message);$('fatal').hidden=false;$('fatal').textContent=e.message;});$('revision').textContent=SOURCE_COMMIT.slice(0,8);apply(defaults);buttons();try{init();}catch(e){state.errors.push(String(e));$('fatal').hidden=false;$('fatal').textContent='WebGL initialization failed: '+e.message;}history().catch(report);refreshRecipes().catch(e=>{$('saveStatus').textContent=e.message;});
