'use strict';
const $=id=>document.getElementById(id), token=document.querySelector('meta[name="bench-token"]').content;
const fields=['label','text','instruct','language','seed','num_step','speed','guidance_scale','effect_preset'];
const numeric=new Set(['seed','num_step','speed','guidance_scale']);
let state={takes:[],recipes:[]}, busy=false, signatures=new Map(), blobs=new Map(), recipeSignature='';
const notice=s=>{$('notice').textContent=s;};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function api(path,body,raw=false){const r=await fetch(new URL('api/'+path,location.href),{method:body===undefined?'GET':'POST',credentials:'omit',headers:{'X-Bench-Token':token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){let d;try{d=await r.json();}catch{d={error:'Connection failed: '+r.status};}throw Error(d.error||'Request failed');}return raw?r.blob():r.json();}
function recipe(){return Object.fromEntries(fields.map(k=>[k,numeric.has(k)?Number($(k).value):$(k).value]));}
function loadRecipe(p){for(const k of fields)if(p[k]!==undefined)$(k).value=p[k];count();notice('Recipe loaded. Change a variable, then queue a new take.');}
function count(){$('count').textContent=$('text').value.length+' / 2000';}
function button(text,fn){const b=el('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message);}finally{b.disabled=false;}};return b;}
function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function jsonDownload(d,name){download(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),name);}
async function audioURL(t){if(!blobs.has(t.id))blobs.set(t.id,URL.createObjectURL(await api('audio/'+t.id,undefined,true)));return blobs.get(t.id);}
function player(t,parent){const box=el('div');const b=button('Load audio · '+t.audio.duration+'s',async()=>{const a=el('audio');a.controls=true;a.preload='metadata';a.src=await audioURL(t);a.onplay=()=>document.querySelectorAll('audio').forEach(other=>{if(other!==a)other.pause();});box.replaceChildren(a);});box.append(b);parent.append(box);}
function compare(side){const value=$('select'+side).value,box=$('slot'+side);box.replaceChildren();const t=state.takes.find(t=>t.id===value);if(!t){box.textContent='Choose a completed take.';return;}box.append(el('div',t.recipe.instruct||'No voice direction'));player(t,box);box.append(el('div',`Seed ${t.recipe.seed} · ${t.recipe.num_step} steps · ${t.recipe.speed}× · ${t.elapsed}s compute`));}
function card(t){const a=el('article');a.dataset.id=t.id;const top=el('div',undefined,'card-top');top.append(el('h3',t.recipe.label),el('span',t.status,'badge '+t.status));a.append(top);const p=t.recipe;a.append(el('div',`Seed ${p.seed} · ${p.num_step} steps · ${p.speed}× · guidance ${p.guidance_scale} · ${p.effect_preset}${t.elapsed!==undefined?' · '+t.elapsed+'s compute':''}`,'info'));a.append(el('div',p.text,'passage'));if(t.status==='running')a.append(el('p','Generating on Studio. This includes model warm-up; the bench cannot interrupt running inference.','hint'));if(t.error)a.append(el('p',t.error,'error'));if(t.status==='done')player(t,a);
const actions=el('div',undefined,'actions');actions.append(button('Reuse recipe',()=>loadRecipe(p)),button('Export recipe',()=>jsonDownload({version:1,recipe:p,notes:t.notes},'omnivoice-'+t.id.slice(0,8)+'.json')));
const star=button(t.favorite?'★ Favorite':'☆ Favorite',async()=>{const d=await api('takes/'+t.id,{favorite:!t.favorite});t.favorite=d.favorite;star.textContent=t.favorite?'★ Favorite':'☆ Favorite';await refresh();});actions.append(star);
if(t.status==='done'){for(const side of ['A','B'])actions.append(button('→ '+side,()=>{$('select'+side).value=t.id;compare(side);}));actions.append(button('Download WAV',async()=>download(await api('audio/'+t.id,undefined,true),'omnivoice-'+t.id.slice(0,8)+'.wav')));}
if(t.status==='queued')actions.append(button('Cancel queued',async()=>{await api('takes/'+t.id,{cancel:true});await refresh();}));a.append(actions);
const label=el('label','Listening notes');const notes=el('textarea');notes.className='notes';notes.maxLength=2000;notes.rows=2;notes.value=t.notes;notes.placeholder='Tone, pacing, pronunciation…';notes.setAttribute('aria-label','Listening notes for '+p.label);const saved=el('span','','note-state');let timer;async function save(){try{const updated=await api('takes/'+t.id,{notes:notes.value});t.notes=updated.notes;saved.textContent='Saved';}catch(e){saved.textContent='Not saved';notice(e.message);}}notes.oninput=()=>{saved.textContent='Saving…';clearTimeout(timer);timer=setTimeout(save,650);};notes.onchange=()=>{clearTimeout(timer);save();};label.append(notes,saved);a.append(label);
const detail=el('details');detail.append(el('summary','Exact recipe'),el('pre',JSON.stringify(p,null,2),'recipe-view'));a.append(detail);return a;}
function render(){const takes=state.takes,filtered=takes.filter(t=>!$('favorites').checked||t.favorite);$('totals').textContent=takes.length+' TAKES';const container=$('takes');if(filtered.length){container.querySelector('.empty')?.remove();for(const t of filtered){const sig=JSON.stringify([t.status,t.error,t.favorite]);let existing=container.querySelector('[data-id="'+t.id+'"]');if(!existing){existing=card(t);container.append(existing);}else if(signatures.get(t.id)!==sig&&!existing.contains(document.activeElement)){existing.replaceWith(card(t));}signatures.set(t.id,sig);}container.querySelectorAll('article').forEach(a=>{if(!filtered.some(t=>t.id===a.dataset.id))a.remove();});const sorted=filtered.map(t=>container.querySelector('[data-id="'+t.id+'"]'));sorted.forEach((a,i)=>{if(container.children[i]!==a)container.insertBefore(a,container.children[i]||null);});}else container.replaceChildren(el('div',takes.length?'No favorite takes yet.':'Your first experiment starts on the left.','empty'));
for(const side of ['A','B']){const s=$('select'+side),v=s.value,done=takes.filter(t=>t.status==='done');const keys=done.map(t=>t.id).join();if(s.dataset.keys!==keys){s.replaceChildren(new Option('Choose a completed take',''));done.forEach(t=>s.add(new Option(t.recipe.label+' · '+t.recipe.seed,t.id)));s.value=v;s.dataset.keys=keys;}}
const rs=JSON.stringify(state.recipes);if(rs!==recipeSignature){$('recipes').replaceChildren(...state.recipes.map(r=>button(r.name,()=>loadRecipe(r.recipe))));recipeSignature=rs;}
$('generate').disabled=state.paused||takes.filter(t=>['queued','running'].includes(t.status)).length>=8;if(state.paused)notice('Queue paused after an uncertain Studio failure. Check Studio before restarting the bench.');}
async function refresh(){if(busy)return;busy=true;try{state=await api('state');render();}catch(e){notice(e.message);}finally{busy=false;}}
async function status(){try{const d=await api('status');$('status').textContent=d.online?`${String(d.device).toUpperCase()} · ${d.model||'connected'}`:'Studio offline';$('dot').className=d.online?'online':'';$('status').title=d.error||d.detail||'';}catch(e){$('status').textContent='Connection unavailable';$('dot').className='';notice(e.message);}}
$('compose').onsubmit=async e=>{e.preventDefault();$('generate').disabled=true;try{await api('takes',recipe());notice('Take queued. You can keep composing while Studio generates.');await refresh();}catch(e){notice(e.message);}finally{$('generate').disabled=false;}};
$('text').oninput=count;$('random').onclick=()=>{$('seed').value=crypto.getRandomValues(new Uint32Array(1))[0]%2147483648;};
const presets={narrator:['Warm narrator','male, middle-aged, low pitch, british accent'],character:['Quiet character','female, young adult, moderate pitch, whisper, american accent'],announcer:['Bright announcer','male, young adult, moderate pitch, american accent']};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];$('label').value=p[0];$('instruct').value=p[1];});
$('saveRecipe').onclick=async()=>{try{await api('recipes',{name:$('recipeName').value,recipe:recipe()});notice('Recipe saved on this host.');await refresh();}catch(e){notice(e.message);}};
$('export').onclick=async()=>{try{const fresh=await api('state');jsonDownload({version:1,exported:new Date().toISOString(),...fresh},'omnivoice-notebook.json');}catch(e){notice(e.message);}};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>16000)throw Error('Choose a single recipe JSON file under 16 KB.');const d=JSON.parse(await f.text()),p=d.recipe;if(!p||typeof p.text!=='string'||!fields.every(k=>k in p)||Object.keys(p).some(k=>!fields.includes(k)))throw Error('Expected an exported single recipe, not a full notebook.');if(p.text.length>2000||p.instruct.length>800)throw Error('Recipe exceeds text limits');loadRecipe(p);}catch(e){notice('Import failed: '+e.message);}finally{e.target.value='';}};
$('favorites').onchange=render;for(const s of ['A','B'])$('select'+s).onchange=()=>compare(s);count();refresh();status();setInterval(refresh,3000);setInterval(status,15000);
