import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';
import {createBuildQueue} from '../server/build-queue.mjs';
const workspace_id='eed047a8-e519-495e-a7ca-1c8c150a6ef4';
function fixture(t){const directory=mkdtempSync(path.join(os.tmpdir(),'orbit-queue-'));let calls=[],run={},fail;const q=createBuildQueue({directory,interval:0,context:()=>'',upstream:async(p,b)=>{calls.push([p,b]);if(fail)throw fail;if(p==='/v1/runs'){run={session_id:b.session_id,status:'running',run_id:'run_queue_testing'};return run;}return run;}});t.after(()=>{q.close();rmSync(directory,{recursive:true,force:true});});const read=()=>q.action({workspace_id,operation:'read'});const act=async(operation,extra={})=>q.action({workspace_id,operation,base_revision:(await read()).revision,...extra});return {q,read,act,calls,directory,set:(v)=>Object.assign(run,v),fail:(v)=>fail=v};}
test('queue submits once, serializes tasks, retains evidence and completes',async t=>{const f=fixture(t);await f.act('add',{input:'first'});await f.act('add',{input:'second'});await f.act('start',{confirm:true});await Promise.all([f.q.tick(),f.q.tick()]);assert.equal(f.calls.filter(c=>c[0]==='/v1/runs').length,1);await f.q.tick();assert.equal(f.calls.filter(c=>c[0]==='/v1/runs').length,1);f.set({status:'completed',output:'Verified output\n[WORKSHOP_DONE]'});await f.q.tick();assert.equal((await f.read()).tasks[0].status,'completed');await f.q.tick();assert.equal(f.calls.filter(c=>c[0]==='/v1/runs').length,2);});
test('unverified completion blocks next task',async t=>{const f=fixture(t);await f.act('add',{input:'one'});await f.act('start',{confirm:true});await f.q.tick();f.set({status:'completed',output:'I need clarification.'});await f.q.tick();assert.equal((await f.read()).enabled,false);assert.equal((await f.read()).tasks[0].status,'blocked');await assert.rejects(f.act('start',{confirm:true}),/Review/);});
test('busy submission is queued but never retried automatically',async t=>{const f=fixture(t);await f.act('add',{input:'one'});await f.act('start',{confirm:true});f.fail(Object.assign(Error('busy'),{status:429}));await f.q.tick();await f.q.tick();assert.equal(f.calls.length,1);assert.equal((await f.read()).tasks[0].status,'queued');assert.equal((await f.read()).enabled,false);});
test('ambiguous network failure blocks replay',async t=>{const f=fixture(t);await f.act('add',{input:'one'});await f.act('start',{confirm:true});f.fail(Error('timeout'));await f.q.tick();assert.equal((await f.read()).tasks[0].status,'blocked');await assert.rejects(f.act('start',{confirm:true}));});
test('approval pauses queue; explicit approval resumes run only',async t=>{const f=fixture(t);await f.act('add',{input:'one'});await f.act('start',{confirm:true});await f.q.tick();f.set({status:'waiting_for_approval'});await f.q.tick();let d=await f.read();assert.equal(d.enabled,false);await f.act('approval',{task_id:d.tasks[0].id,choice:'once',confirm:true});assert.equal((await f.read()).enabled,false);assert.equal(f.calls.at(-1)[0],'/v1/runs/run_queue_testing/approval');});
test('restart retains tasks and run ID but starts paused; revision protects edits',async t=>{const f=fixture(t);await f.act('add',{input:'one'});await f.act('start',{confirm:true});await f.q.tick();const q=createBuildQueue({directory:f.directory,interval:0,context:()=>'',upstream:async()=>{throw Error('unexpected');}});t.after(()=>q.close());const d=await q.action({workspace_id,operation:'read'});assert.equal(d.enabled,false);assert.equal(d.tasks[0].run,'run_queue_testing');await assert.rejects(q.action({workspace_id,operation:'add',base_revision:0,input:'bad'}),/changed/);await assert.rejects(q.action({workspace_id:'../x',operation:'read'}),/Invalid workspace/);});
test('pause and stop do not launch the next task',async t=>{const f=fixture(t);await f.act('add',{input:'one'});await f.act('start',{confirm:true});await f.q.tick();await f.act('stop',{task_id:(await f.read()).tasks[0].id,confirm:true});assert.equal(f.calls.at(-1)[0],'/v1/runs/run_queue_testing/stop');assert.equal((await f.read()).enabled,false);});
