from pathlib import Path
from playwright.sync_api import sync_playwright, expect
R=Path(__file__).resolve().parents[1]
env=dict(x.split('=',1) for x in (R/'.env.deploy').read_text().splitlines() if '=' in x)
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,args=['--no-sandbox'])
 page=b.new_page(viewport={'width':1440,'height':1000}); errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('https://kimi.tailec998.ts.net:4325/',wait_until='networkidle')
 page.get_by_role('button',name='Connect local host',exact=True).click()
 page.get_by_role('textbox',name='Host session token').fill(env['ORBIT_TOKEN'])
 page.get_by_role('button',name='Unlock local host',exact=True).click()
 page.wait_for_timeout(1800)
 page.get_by_role('button',name='Show desktop shortcuts',exact=True).click()
 icon=page.get_by_role('button',name='Open Plugin Manager',exact=True)
 expect(icon).to_be_visible()
 assert icon.evaluate("e => e.parentElement.classList.contains('desktop-icons')")
 icon.click()
 dialog=page.get_by_role('dialog',name='Workspace plugins',exact=True)
 expect(dialog.get_by_role('heading',name='Orbit Desktop · Plugin Manager')).to_be_visible()
 expect(dialog.locator('.plugin-card')).to_have_count(13)
 search=dialog.get_by_role('searchbox',name='Search desktop plugins')
 search.fill('hermes-live-tools');expect(dialog.locator('.plugin-card')).to_have_count(1)
 search.fill('nonexistent-xyz');expect(dialog).to_contain_text('No matching plugins')
 search.fill('workspace-workshop')
 dialog.get_by_role('button',name='Install plugin workspace-workshop',exact=True).click()
 expect(dialog.get_by_role('button',name='Enable plugin workspace-workshop',exact=True)).to_be_visible()
 dialog.get_by_role('button',name='Enable plugin workspace-workshop',exact=True).click()
 expect(dialog.get_by_role('button',name='Disable plugin workspace-workshop',exact=True)).to_be_visible()
 dialog.get_by_role('combobox',name='Plugin status filter').select_option('Enabled')
 expect(dialog.locator('.plugin-card')).to_have_count(1)
 dialog.get_by_role('button',name='Disable plugin workspace-workshop',exact=True).click()
 expect(dialog.locator('.plugin-card')).to_have_count(0)
 dialog.get_by_role('combobox',name='Plugin status filter').select_option('Installed')
 expect(dialog.locator('.plugin-card')).to_have_count(1)
 page.once('dialog',lambda d:d.accept())
 dialog.get_by_role('button',name='Remove plugin workspace-workshop',exact=True).click()
 expect(dialog.locator('.plugin-card')).to_have_count(0)
 dialog.get_by_role('combobox',name='Plugin status filter').select_option('All plugins')
 search.fill('');expect(dialog.locator('.plugin-card')).to_have_count(13)
 page.screenshot(path=str(R/'.runtime/desktop-plugin-catalog.png'))
 assert not errors,errors
 b.close()
 print('PASS: served catalog renders 13 cards; search, empty state, filters, real authenticated install/enable/disable/remove in isolated workspace; no JavaScript errors.')
