from playwright.sync_api import sync_playwright, expect
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from orbit_menu import menu, open_menu, close_menu

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, args=['--no-sandbox'])
    page = browser.new_page(viewport={'width': 1400, 'height': 950})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto('https://kimi.tailec998.ts.net:4325/', wait_until='networkidle')
    page.add_init_script('''if (!sessionStorage.getItem('global-opacity-seeded')) { sessionStorage.setItem('global-opacity-seeded','1'); const s=JSON.parse(localStorage.getItem('orbit.workspace.v1')); s.view='windows'; s.appearance={fullViewport:true}; s.monitors=s.monitors.slice(0,2); s.selected=s.monitors[0].id; s.monitors.forEach((m,i)=>{m.opacity=i?0.8:0.5;m.frame={x:10+i*600,y:10,width:580,height:750,z:i+1};m.layout={type:'pane',pane:{id:'global-opacity-test-'+i,kind:'browser',url:'orbit://welcome'}};});localStorage.setItem('orbit.workspace.v1',JSON.stringify(s)); }''')
    page.reload(wait_until='networkidle')
    button = page.get_by_role('button', name='Global transparency options', exact=True)
    dialog = page.get_by_role('dialog', name='Global transparency', exact=True)
    wins = page.locator('.monitor')
    open_menu(page)
    expect(button).to_be_visible()
    button.click()
    expect(dialog).to_be_visible()
    expect(wins.nth(0)).to_have_css('opacity', '0.5')
    dialog.get_by_role('slider', name='All windows opacity').fill('65')
    for i in range(2): expect(wins.nth(i)).to_have_css('opacity', '0.65')
    dialog.get_by_role('button', name='Restore previous individual opacity settings').click()
    expect(wins.nth(0)).to_have_css('opacity', '0.5')
    expect(wins.nth(1)).to_have_css('opacity', '0.8')
    button.click()
    dialog.get_by_role('slider', name='All windows opacity').fill('70')
    dialog.get_by_role('button', name='Close global transparency').click()
    page.wait_for_timeout(350)
    page.reload(wait_until='networkidle')
    for i in range(2): expect(wins.nth(i)).to_have_css('opacity', '0.7')
    open_menu(page)
    button.click()
    dialog.get_by_role('button', name='Make all windows fully opaque').click()
    for i in range(2): expect(wins.nth(i)).to_have_css('opacity', '1')
    page.keyboard.press('Escape')
    expect(dialog).to_have_count(0)
    page.get_by_role('button', name='Exit full viewport', exact=True).click()
    open_menu(page)
    expect(button).to_be_visible()
    menu(page,'Switch to spatial view')
    button.click()
    dialog.get_by_role('slider', name='All windows opacity').fill('55')
    for i in range(2): expect(wins.nth(i)).to_have_css('opacity', '0.55')
    page.keyboard.press('Escape')
    assert not errors, errors
    print('PASS: global button in full/normal viewport, live bulk opacity in windows/spatial, undo preserves mixed settings, reset, Escape, reload persistence; no JS errors. Isolated workspace.')
    browser.close()
