import test from 'node:test';
import assert from 'node:assert/strict';
import { initial,validate,leaves } from '../src/model.ts';
import { applyOperation } from '../src/workspace-ops.ts';
import { spatialWindow,tileSpatial,defaultCamera } from '../src/spatial-layout.ts';
test('legacy spatial migration does not mutate windows',()=>{const state=initial(),before=structuredClone(state);const s=spatialWindow(state.monitors[0],state.monitors,state.arc);assert.equal(s.resolution,1920);assert.ok(s.width>0);assert.deepEqual(state,before);});
test('all spatial tiles retain pane identities and 2D geometry',()=>{for(const mode of ['grid','row','curve']){const state=initial(),ids=state.monitors.flatMap(m=>leaves(m.layout).map(p=>p.id));state.monitors[0].frame={x:10,y:20,width:800,height:600,z:1};const next=applyOperation(state,{action:'arrange_spatial',mode,columns:2});assert.equal(next.view,'spatial');assert.deepEqual(next.monitors.flatMap(m=>leaves(m.layout).map(p=>p.id)),ids);assert.deepEqual(next.monitors[0].frame,state.monitors[0].frame);assert.ok(next.monitors.every(m=>m.spatial.resolution===1920));assert.ok(next.monitors[0].spatial.x!==next.monitors[1].spatial.x);validate(next);}});
test('free xyz, independent dimensions and camera round trip',()=>{let state=initial();tileSpatial(state.monitors,'grid');const spatial={...state.monitors[0].spatial,x:100,y:-100,z:80,width:15,height:12,resolution:3840,yaw:160,pitch:70};state=applyOperation(state,{action:'update_window',window_id:state.selected,spatial});state=applyOperation(state,{action:'set_spatial_camera',camera:{...defaultCamera(),distance:500,azimuth:3}});assert.deepEqual(validate(JSON.parse(JSON.stringify(state))),state);});
test('invalid spatial values and tile inputs reject atomically',()=>{const state=initial();tileSpatial(state.monitors,'grid');const before=structuredClone(state);for(const patch of [{x:NaN},{height:0},{width:201},{resolution:9000},{pitch:90}])assert.throws(()=>applyOperation(state,{action:'update_window',window_id:state.selected,spatial:{...state.monitors[0].spatial,...patch}}));for(const op of [{mode:'bad'},{columns:0},{gap:-1},{window_ids:['missing']}])assert.throws(()=>applyOperation(state,{action:'arrange_spatial',...op}));assert.deepEqual(state,before);assert.throws(()=>validate({...state,spatialCamera:{...defaultCamera(),distance:Infinity}}));});
