from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, args=['--no-sandbox'])
    page = browser.new_page(viewport={'width': 1600, 'height': 1000})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto('https://kimi.tailec998.ts.net:4325/', wait_until='networkidle')
    page.evaluate('''() => { const s=JSON.parse(localStorage.getItem('orbit.workspace.v1')); s.view='windows'; s.appearance={fullViewport:true}; s.monitors=s.monitors.slice(0,2); s.monitors.forEach((m,i)=>{m.opacity=1;m.frame={x:10+i*760,y:10,width:750,height:800,z:i+1};m.layout={type:'pane',pane:{id:'controls-test-'+i,kind:'agent',url:'orbit://welcome'}};});s.selected=s.monitors[1].id;localStorage.setItem('orbit.workspace.v1',JSON.stringify(s)); }''')
    page.reload(wait_until='networkidle')
    from pathlib import Path
    env = dict(x.split('=', 1) for x in (Path(__file__).resolve().parents[1] / '.env.deploy').read_text().splitlines() if '=' in x)
    def unlock():
        page.get_by_role('button', name='Connect local host', exact=True).click()
        page.get_by_role('textbox', name='Host session token').fill(env['ORBIT_TOKEN'])
        page.get_by_role('button', name='Unlock local host', exact=True).click()
    unlock()
    monitor_id = page.locator('.monitor').first.get_attribute('data-monitor-id')
    win = page.locator(f'[data-monitor-id="{monitor_id}"]')
    win.get_by_role('button', name='Settings for', exact=False).click()
    options = page.get_by_role('dialog', name='Window options', exact=True)
    expect(options).to_be_visible()
    options.get_by_role('textbox', name='Window name', exact=True).fill('Options regression')
    options.get_by_role('button', name='Save window name').click()
    expect(win.locator('.monitor-bar strong')).to_have_text('Options regression')
    options.get_by_role('slider', name='Window opacity').fill('60')
    expect(win).to_have_css('opacity', '0.6')
    options.get_by_role('slider', name='Text size').fill('21')
    options.get_by_role('button', name='Reset window opacity').click()
    expect(win).to_have_css('opacity', '1')
    page.keyboard.press('Escape')
    expect(options).to_have_count(0)
    win.get_by_role('button', name='Settings for Options regression', exact=True).click()
    expect(options).to_be_visible()
    expect(options.get_by_role('slider', name='Text size')).to_have_value('21')
    options.get_by_role('button', name='Close window options').click()
    win.get_by_role('button', name='Toggle transparency', exact=False).click()
    dialog = page.get_by_role('dialog', name='Window transparency', exact=True)
    expect(dialog).to_be_visible()
    dialog.get_by_role('slider', name='Window opacity').fill('45')
    expect(win).to_have_css('opacity', '0.45')
    expect(page.locator('.monitor').nth(1)).to_have_css('opacity', '1')
    dialog.get_by_role('button', name='Close transparency settings').click()
    if win.get_by_role('button', name='Rename this agent conversation').count() == 0:
        win.locator('select').first.select_option('agent')
        page.get_by_role('button', name='Confirm change', exact=True).click()
    win.get_by_role('button', name='Rename this agent conversation').click()
    rename = page.get_by_role('dialog', name='Rename agent conversation')
    rename.get_by_role('textbox', name='New conversation name').fill('Creative partner')
    rename.get_by_role('button', name='Save conversation name').click()
    expect(win.get_by_role('textbox', name='Conversation title')).to_have_value('Creative partner')
    page.wait_for_timeout(400)
    page.reload(wait_until='networkidle')
    expect(win).to_have_css('opacity', '0.45')
    expect(win.get_by_role('textbox', name='Conversation title')).to_have_value('Creative partner')
    if win.get_by_role('button', name='Rename this agent conversation').count() == 0:
        win.locator('select').first.select_option('agent')
        page.get_by_role('button', name='Confirm change', exact=True).click()
    win.get_by_role('button', name='Rename this agent conversation').click()
    rename.get_by_role('textbox', name='New conversation name').fill('Discard')
    rename.get_by_role('button', name='Cancel rename').click()
    expect(win.get_by_role('textbox', name='Conversation title')).to_have_value('Creative partner')
    win.get_by_role('button', name='Toggle transparency', exact=False).click()
    dialog.get_by_role('button', name='Make window fully opaque').click()
    expect(win).to_have_css('opacity', '1')
    assert not errors, errors
    print('PASS: unselected-window click, full-viewport opacity dialog, live opacity, isolation, rename/save/cancel, reload persistence, opaque reset; no JS errors. Isolated browser workspace, no agent requests.')
    browser.close()
