import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {createHmac,randomUUID} from 'node:crypto';
import {SqliteWorkspaceStore} from '../server/sqlite-workspace-store.mjs';
import {WorkbenchStore} from '../server/workbench-store.mjs';
import {WorkbenchData} from '../server/workbench-data.mjs';
import {createWorkbenchExecution} from '../server/workbench-execution.mjs';
import {createWorkbenchNative} from '../server/workbench-native.mjs';
import {openProjectRoot} from '../server/project-files.mjs';
import {commandIdentity} from '../server/command-identity.mjs';
import {initial} from '../src/model.ts';
import {HERMES_NATIVE_CONTRACT} from '../contracts/workbench-native-v1.mjs';
import {validateWorkbenchProvenance} from '../contracts/workbench-result-v1.mjs';
import {createWorkbenchBuildIdentity} from '../server/workbench-build-identity.mjs';
import {pathToFileURL} from 'node:url';
const wait=()=>new Promise(resolve=>setTimeout(resolve,5));
test('source recorder identity is a startup snapshot despite subsequent on-disk changes',t=>{
  const root=fs.mkdtempSync('/tmp/opencode/sol-build-identity-'),server=path.join(root,'server'),contracts=path.join(root,'contracts');fs.mkdirSync(server);fs.mkdirSync(contracts);
  t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  fs.writeFileSync(path.join(server,'one.mjs'),'export const value=1;');fs.writeFileSync(path.join(contracts,'one.mjs'),'export const contract=1;');
  const serverURL=pathToFileURL(server+'/'),contractURL=pathToFileURL(contracts+'/'),first=createWorkbenchBuildIdentity(serverURL,contractURL),identity=first();
  fs.writeFileSync(path.join(server,'one.mjs'),'export const value=2;');
  assert.equal(first(),identity);assert.notEqual(createWorkbenchBuildIdentity(serverURL,contractURL)(),identity);
});
async function privateCall(channel,args,seq){
  const raw=JSON.stringify(args),mac=createHmac('sha256',channel.secret).update(`${seq}\n${raw}`).digest('hex');
  return new Promise((resolve,reject)=>{const req=http.request({socketPath:channel.socket,path:'/tool',method:'POST',headers:{'content-type':'application/json','x-orbit-grant':channel.grant_id,'x-orbit-sequence':String(seq),'x-orbit-mac':mac}},res=>{let body='';res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve(JSON.parse(body)));});req.on('error',reject);req.end(raw);});
}
test('owner and authenticated native checks retain distinct initiator/authorizer/recorder through evidence finalization',async t=>{
  const root=fs.mkdtempSync('/tmp/opencode/sol-provenance-'),projectRoot=path.join(root,'project');fs.mkdirSync(projectRoot);fs.writeFileSync(path.join(projectRoot,'math.js'),'export const sum = (a,b) => a - b;\n');
  const store=new SqliteWorkspaceStore(path.join(root,'runtime')),workspace_id=randomUUID(),pane_id=randomUUID();
  store.commit(commandIdentity({workspace_id,action:'sync',base_revision:0,state:initial(),operation_id:randomUUID(),intent:'Provenance'},'owner'),{create:()=>({id:workspace_id,revision:1,state:initial(),capability:randomUUID(),api:'http://127.0.0.1:4318'})});
  const records=new WorkbenchStore(store),opened=openProjectRoot(projectRoot),project=records.register(workspace_id,{root:projectRoot,name:'Provenance',identity:opened.identity});opened.close();
  const data=new WorkbenchData(store),execution=createWorkbenchExecution({store,records,data}),base={workspace_id,project_id:project.id},call=(action,fields={})=>execution.dispatch({...base,action,...fields});
  let channel;const hermes={readBinding:async()=>({trusted_host:true,sandbox:false,profile_id:'fixture',session_id:'fixture-session',config_generation:1,binding_revision:1,native_runtime:{kind:'local-pinned',commit:HERMES_NATIVE_CONTRACT.commit,model:'fixture',destination:'loopback configured model endpoint',configuration_hash:'0'.repeat(64)}}),startNative:async config=>{channel=config.channel;return {completion:new Promise(()=>{})};},stopNative:async()=>({requested:true})};
  const native=createWorkbenchNative({store,records,data,execution,hermes}),owner=(action,fields={})=>native.dispatch({...base,action,...fields});
  t.after(()=>{native.close();execution.close();store.close();fs.rmSync(root,{recursive:true,force:true});});
  const {task}=await call('task_create',{title:'Check origin',acceptance_statement:'sum must add',check_definition_id:'host-regression',profile_id:'fixture',session_id:'fixture-session',pane_id});
  const p=await call('candidate_preview',{task_id:task.id}),{candidate}=await call('candidate_create',{task_id:task.id,preview_id:p.preview_id,preview_digest:p.preview.digest});
  const preview=await call('check_preview',{candidate_id:candidate.id,definition_id:'host-regression'}),op_id=randomUUID();
  const ownerRun=await call('check_run',{candidate_id:candidate.id,preview_id:preview.preview_id,preview_digest:preview.preview.spec_digest,op_id});
  assert.equal(ownerRun.job.provenance.initiated_by.kind,'owner_action');assert.equal(ownerRun.evidence.provenance.authorized_by.kind,'owner_approval');
  assert.equal(ownerRun.evidence.provenance.recorded_by.kind,'comet_service');
  const {attempt}=await call('attempt_create',{task_id:task.id,candidate_id:candidate.id,profile_id:'fixture',session_id:'fixture-session',pane_id});
  const scope=await owner('preview',{attempt_id:attempt.id,context_ids:[],budget:{calls:5,checks:1,duration_ms:90000}}),{grant}=await owner('approve',{preview_id:scope.preview_id,preview_digest:scope.preview_digest});
  await owner('start',{grant_id:grant.id});
  assert.equal((await privateCall(channel,{action:'job_start',candidate_id:randomUUID()},1)).ok,false);
  const actual=await privateCall(channel,{action:'job_start'},2);assert.equal(actual.ok,true,JSON.stringify(actual));
  const job=actual.result.job,evidence=actual.result.evidence;
  assert.equal(job.provenance.initiated_by.kind,'native_agent');assert.equal(job.provenance.initiated_by.attempt_id,attempt.id);
  assert.equal(job.provenance.initiated_by.grant_id,grant.id);assert.equal(job.provenance.initiated_by.tool_call_id,job.op_id);
  assert.equal(job.provenance.authorized_by.authority_generation,grant.authority_generation);
  assert.equal(job.provenance.recorded_by.build_id.length,64);assert.equal(job.provenance.recorded_by.verifier_id,'host-regression');
  assert.equal(validateWorkbenchProvenance(job.provenance),true);assert.deepEqual(evidence.provenance,job.provenance);
  assert.equal(evidence.actor,'native_agent');
  const replay=await call('job_get',{job_id:job.id});assert.deepEqual(replay.evidence[0].provenance,job.provenance);
  await wait();
});
