import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {createWorkbenchEnvironments,environmentSchema} from '../server/workbench-environments.mjs';
import {SqliteWorkspaceStore} from '../server/sqlite-workspace-store.mjs';
import {WorkbenchStore} from '../server/workbench-store.mjs';
import {WorkbenchData} from '../server/workbench-data.mjs';
import {createWorkbenchExecution} from '../server/workbench-execution.mjs';
import {openProjectRoot} from '../server/project-files.mjs';
import {initial} from '../src/model.ts';
import {commandIdentity} from '../server/command-identity.mjs';

const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
test('offline locked file tarball dependency prepares privately and executes a test import',async t=>{
  const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'orbit-environment-'));
  t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
  const library=path.join(tmp,'library');fs.mkdirSync(library);
  fs.writeFileSync(path.join(library,'package.json'),JSON.stringify({name:'fixture-lib',version:'1.0.0',main:'index.js',scripts:{install:'exit 99'}}));
  fs.writeFileSync(path.join(library,'index.js'),'module.exports = 41;\n');
  const packed=spawnSync(process.execPath,[path.resolve(path.dirname(process.execPath),'../lib/node_modules/npm/bin/npm-cli.js'),'pack','--ignore-scripts','--offline','--pack-destination',tmp],{cwd:library,encoding:'utf8',env:{PATH:path.dirname(process.execPath),HOME:tmp,NPM_CONFIG_CACHE:path.join(tmp,'cache'),NPM_CONFIG_REGISTRY:'http://127.0.0.1:9/'}});
  assert.equal(packed.status,0,packed.stderr);
  const tarball=fs.readFileSync(path.join(tmp,'fixture-lib-1.0.0.tgz'));
  const project=path.join(tmp,'project');fs.mkdirSync(path.join(project,'vendor'),{recursive:true});
  const pkg={name:'fixture-project',version:'1.0.0',dependencies:{'fixture-lib':'file:vendor/fixture-lib-1.0.0.tgz'}};
  const lock={name:pkg.name,version:pkg.version,lockfileVersion:3,requires:true,packages:{'':{name:pkg.name,version:pkg.version,dependencies:pkg.dependencies},'node_modules/fixture-lib':{version:'1.0.0',resolved:'file:vendor/fixture-lib-1.0.0.tgz',integrity:`sha512-${createHash('sha512').update(tarball).digest('base64')}`}}};
  const sources={'package.json':JSON.stringify(pkg),'package-lock.json':JSON.stringify(lock),'vendor/fixture-lib-1.0.0.tgz':tarball,'fixture.test.cjs':'const assert=require("node:assert/strict");assert.equal(require("fixture-lib"),42);\n'};
  for(const [name,content] of Object.entries(sources)){fs.mkdirSync(path.dirname(path.join(project,name)),{recursive:true});fs.writeFileSync(path.join(project,name),content);}
  const store=new SqliteWorkspaceStore(path.join(tmp,'runtime')),workspace_id=randomUUID();
  t.after(()=>store.close());
  store.commit(commandIdentity({workspace_id,action:'sync',base_revision:0,state:initial(),operation_id:randomUUID()},'owner'),{create:()=>({id:workspace_id,revision:1,state:initial(),capability:randomUUID()})});
  const records=new WorkbenchStore(store),data=new WorkbenchData(store);
  const opened=openProjectRoot(project),registered=records.register(workspace_id,{root:project,name:'Offline dependency fixture',identity:opened.identity});opened.close();
  const project_id=registered.id,execution=createWorkbenchExecution({store,records,data});
  const call=(action,fields={})=>execution.dispatch({action,workspace_id,project_id,...fields});
  const {task}=await call('task_create',{title:'Repair failing import test',acceptance_statement:'dependency test passes',check_definition_id:'node-test',profile_id:'default',session_id:'fixture'});
  const candidatePreview=await call('candidate_preview',{task_id:task.id});
  const {candidate}=await call('candidate_create',{task_id:task.id,preview_id:candidatePreview.preview_id,preview_digest:candidatePreview.preview.digest});
  const candidate_id=candidate.id;
  const env=createWorkbenchEnvironments({store,records,data});
  const base={workspace_id,project_id};
  assert.equal(environmentSchema.oneOf.length,4);
  const preview=await env.dispatch({...base,action:'profile_preview',candidate_id,required_inputs:['package.json','package-lock.json','vendor/fixture-lib-1.0.0.tgz']});
  assert.deepEqual(preview.command.slice(0,4),['/usr/bin/timeout','--kill-after=5s','60s',preview.toolchain.node]);
  const approved=await env.dispatch({...base,action:'profile_approve',preview_id:preview.preview_id,preview_digest:preview.preview_digest});
  const ready=await env.dispatch({...base,action:'environment_prepare',profile_id:approved.id});
  assert.equal(ready.status,'ready');assert.equal(ready.prepared.network_policy,'offline_only');
  assert.equal(fs.existsSync(path.join(project,'node_modules')),false);
  const view=env.createExecutionView({...base,profile_id:approved.id,candidate_id});
  try{
    const first=spawnSync(process.execPath,['fixture.test.cjs'],{cwd:view.root,encoding:'utf8'});
    assert.notEqual(first.status,0,'the intentionally wrong assertion fails with the installed library');
    fs.writeFileSync(path.join(view.root,'fixture.test.cjs'),'const assert=require("node:assert/strict");assert.equal(require("fixture-lib"),41);\n');
    const repaired=spawnSync(process.execPath,['fixture.test.cjs'],{cwd:view.root,encoding:'utf8'});
    assert.equal(repaired.status,0,repaired.stderr);
    assert.equal(fs.readFileSync(path.join(project,'fixture.test.cjs'),'utf8'),sources['fixture.test.cjs']);
  }finally{view.dispose();}
  await assert.rejects(env.dispatch({...base,action:'profile_preview',candidate_id,required_inputs:['package.json','package-lock.json']}),{code:'unsupported'});
  const file=await call('candidate_read',{candidate_id,path:'fixture.test.cjs'});
  const edited=await call('candidate_edit',{candidate_id,path:'fixture.test.cjs',expected_hash:file.file.hash,content:'const assert=require("node:assert/strict");assert.equal(require("fixture-lib"),41);\n'});
  assert.notEqual(edited.candidate.hash,candidate.hash);
  const repairedView=env.createExecutionView({...base,profile_id:approved.id,candidate_id});
  assert.equal(repairedView.prepared.source_hash,edited.candidate.hash);
  repairedView.dispose();
  const installed=path.join(ready.prepared.dependency_root,'fixture-lib','index.js');
  fs.writeFileSync(installed,'module.exports = 0;\n');
  assert.throws(()=>env.createExecutionView({...base,profile_id:approved.id,candidate_id}),{code:'stale_resource'});
  await assert.rejects(env.dispatch({...base,action:'environment_prepare',profile_id:approved.id}),{code:'busy'});
});
