import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {randomUUID} from 'node:crypto';
import {SqliteWorkspaceStore} from '../server/sqlite-workspace-store.mjs';
import {WorkbenchStore} from '../server/workbench-store.mjs';
import {WorkbenchData} from '../server/workbench-data.mjs';
import {createWorkbenchContext} from '../server/workbench-context.mjs';
import {createWorkbenchTerminalSource} from '../server/workbench-terminal-source.mjs';
import {workbenchOwnerRoute} from '../server/workbench-owner-route.mjs';
import {ManagedTerminalIdentityLedger} from '../server/managed-terminal-ledger.mjs';
import {ManagedTerminalProvider} from '../server/managed-terminal-provider.mjs';
import {ManagedTerminalBroker} from '../server/managed-terminal-broker.mjs';
import {openProjectRoot} from '../server/project-files.mjs';
import {commandIdentity} from '../server/command-identity.mjs';
import {initial} from '../src/model.ts';

test('actual tmux observe lease crosses authenticated context capture and preview; invalid authority never does',async t=>{
  const root=fs.mkdtempSync('/tmp/opencode/comet-lease-boundary-'),socket='comet-'+randomUUID();
  const env={PATH:'/usr/bin:/bin',HOME:root,TMUX_TMPDIR:root,TERM:'xterm-256color'};
  const exec=promisify(execFile),tmux=(...args)=>exec('/usr/bin/tmux',['-L',socket,'-f','/dev/null',...args],{env,timeout:5000});
  const store=new SqliteWorkspaceStore(path.join(root,'runtime'));
  let provider,context,server,broker;
  t.after(async()=>{context?.close?.();broker?.dispose?.();await provider?.dispose();if(server)await new Promise(resolve=>server.close(resolve));try{await tmux('kill-server');}catch{}store.close();fs.rmSync(root,{recursive:true,force:true});});
  function workspace(){const id=randomUUID(),state=initial();store.commit(commandIdentity({workspace_id:id,action:'sync',base_revision:0,state,operation_id:randomUUID(),intent:'Synthetic lease boundary'},'owner'),{create:()=>({id,revision:1,state,capability:randomUUID(),api:'http://127.0.0.1:4318'})});return id;}
  const workspace_id=workspace(),foreign=workspace(),pane=store.read(workspace_id).state.monitors[0].layout.pane.id;
  const session='pane-'+pane,ready='ready-'+randomUUID();
  await tmux('new-session','-d','-s',session,`printf 'COMET_REAL_TERMINAL_BYTES\\n'; /usr/bin/tmux -L ${socket} wait-for -S ${ready}; exec /bin/bash --noprofile --norc`);
  await tmux('wait-for',ready);
  const ledgerRoot=path.join(root,'ledger');fs.mkdirSync(ledgerRoot,{mode:0o700});
  const ledger=await new ManagedTerminalIdentityLedger({directory:ledgerRoot}).load();
  provider=await ManagedTerminalProvider.create({mode:'attach',socket,tmuxTmpDir:root,ledger});
  let now=Date.now();broker=new ManagedTerminalBroker({ownerId:'fixture-owner',providerId:'tmux-fixture',provider,workspaceRead:id=>store.read(id),now:()=>now});
  await broker.adopt({workspaceId:workspace_id,paneId:pane,consent:true,baseRevision:1});
  const records=new WorkbenchStore(store),data=new WorkbenchData(store),projectRoot=path.join(root,'project');fs.mkdirSync(projectRoot);
  const opened=openProjectRoot(projectRoot),project=records.register(workspace_id,{root:projectRoot,name:'Lease boundary',identity:opened.identity});opened.close();
  const resource=records.resource(project.id,`pane:${pane}`,{kind:'terminal',pane_id:pane,state:'linked_metadata_only'});
  records.bind({workspace_id,project_id:project.id,resource_id:resource.id,pane_id:pane,base_revision:1,role:'active_terminal'});
  context=createWorkbenchContext({store,records,data,terminalSource:createWorkbenchTerminalSource({store,records,broker}),hermes:{readBinding:async()=>({profile_id:'fixture',session_id:'fixture-session',binding_revision:1,config_generation:'fixture-generation',trusted_host:true,sandbox:false}),dispatchExact:async()=>{throw Error('No disclosure authorized by this test');},probe:async()=>({configured:true})},purgeIntervalMs:0});
  let handler;
  server=http.createServer((req,res)=>handler(req,res));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const port=server.address().port,origin=`http://127.0.0.1:${port}`,token=randomUUID();
  handler=workbenchOwnerRoute({token,port,devOrigins:[],reply:(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(body));},dispatch:body=>context.dispatch(body)});
  async function request(body){const response=await fetch(origin,{method:'POST',headers:{Origin:origin,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id,project_id:project.id,...body})});return {status:response.status,body:await response.json()};}
  const grant=()=>broker.grant({workspaceId:workspace_id,paneId:pane,scope:'observe',ttlMs:5000,baseRevision:1});
  const lease=await grant();assert.match(lease.lease_id,/^[a-f0-9]{32}$/);
  const capture=lease_id=>request({action:'capture',source:{kind:'terminal',resource_id:resource.id,lease_id}});
  const captured=await capture(lease.lease_id);
  assert.equal(captured.status,200,JSON.stringify(captured.body));
  const preview=await request({action:'preview',context_id:captured.body.context.id,recipient:{pane_id:randomUUID()}});
  assert.equal(preview.status,200,JSON.stringify(preview.body));assert.match(preview.body.text,/COMET_REAL_TERMINAL_BYTES/);
  assert.equal(data.list('disclosures',workspace_id,project.id).length,0,'observation must not disclose');
  for(const source of [{kind:'terminal',resource_id:randomUUID(),lease_id:lease.lease_id},{kind:'terminal',resource_id:resource.id,lease_id:randomUUID()}])assert.notEqual((await request({action:'capture',source})).status,200);
  assert.notEqual((await request({action:'capture',workspace_id:foreign,source:{kind:'terminal',resource_id:resource.id,lease_id:lease.lease_id}})).status,200);
  broker.revoke({leaseId:lease.lease_id});assert.notEqual((await capture(lease.lease_id)).status,200);
  const expired=await grant();now+=6000;assert.notEqual((await capture(expired.lease_id)).status,200);
  const replaced=await grant();await tmux('respawn-pane','-k','-t',session,'/bin/bash --noprofile --norc');assert.notEqual((await capture(replaced.lease_id)).status,200);
});
