import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {SqliteWorkspaceStore} from '../server/sqlite-workspace-store.mjs';
import {WorkbenchStore} from '../server/workbench-store.mjs';
import {WorkbenchData} from '../server/workbench-data.mjs';
import {createWorkbenchGate} from '../server/workbench-gate.mjs';
import {openProjectRoot} from '../server/project-files.mjs';
import {createWorkbenchExecution} from '../server/workbench-execution.mjs';
import {readLiveCandidateDiff} from '../server/workbench-live-diff.mjs';
import {initial} from '../src/model.ts';
import {commandIdentity} from '../server/command-identity.mjs';

test('live candidate detail compares exact historical generations after later edits and refuses altered history',async t=>{
  const root=fs.mkdtempSync('/tmp/opencode/live-diff-'),projectRoot=path.join(root,'project');fs.mkdirSync(projectRoot);
  fs.writeFileSync(path.join(projectRoot,'math.js'),'export const sum=(a,b)=>a-b;\n');
  const store=new SqliteWorkspaceStore(path.join(root,'runtime')),workspace_id=randomUUID();
  store.commit(commandIdentity({workspace_id,action:'sync',base_revision:0,state:initial(),operation_id:randomUUID(),intent:'Fixture'},'owner'),{create:()=>({id:workspace_id,revision:1,state:initial(),capability:randomUUID(),api:'http://127.0.0.1:4318'})});
  const records=new WorkbenchStore(store),data=new WorkbenchData(store),opened=openProjectRoot(projectRoot);
  const project=records.register(workspace_id,{root:projectRoot,name:'Exact diff',identity:opened.identity});opened.close();
  const execution=createWorkbenchExecution({store,records,data,gate:createWorkbenchGate()});
  t.after(()=>{execution.close();store.close();fs.rmSync(root,{recursive:true,force:true});});
  const scope={workspace_id,project_id:project.id},call=(action,fields={})=>execution.dispatch({...scope,action,...fields});
  const {task}=await call('task_create',{title:'Fix sum',acceptance_statement:'sum(2,3)===5',check_definition_id:'host-regression',profile_id:'default',session_id:'orbit-live-diff'});
  const preview=await call('candidate_preview',{task_id:task.id});
  const {candidate}=await call('candidate_create',{task_id:task.id,preview_id:preview.preview_id,preview_digest:preview.preview.digest});
  const original=await call('candidate_read',{candidate_id:candidate.id,path:'math.js'});
  const second=await call('candidate_edit',{candidate_id:candidate.id,path:'math.js',expected_hash:original.file.hash,content:'export const sum=(a,b)=>a+b;\n'});
  const secondFile=await call('candidate_read',{candidate_id:candidate.id,path:'math.js'});
  await call('candidate_edit',{candidate_id:candidate.id,path:'math.js',expected_hash:secondFile.file.hash,content:'export const sum=(a,b)=>Number(a)+Number(b);\n'});
  const privateCandidate=data.get('candidates',workspace_id,project.id,candidate.id);
  const reference={kind:'candidate',id:candidate.id,generation:2,hash:second.candidate.hash};
  const diff=await readLiveCandidateDiff({execution,candidate:privateCandidate,...scope,reference});
  assert.equal(diff.available,true);assert.equal(diff.from.generation,1);assert.equal(diff.to.generation,2);
  assert.equal(diff.files[0].old_text,original.file.text);assert.equal(diff.files[0].new_text,secondFile.file.text);
  assert.equal(JSON.stringify(diff).includes('Number(a)'),false,'current generation is never substituted');
  const oldRoot=privateCandidate.root_history.find(version=>version.generation===1).root;
  fs.writeFileSync(path.join(oldRoot,'math.js'),'tampered historical tree\n');
  const unavailable=await readLiveCandidateDiff({execution,candidate:privateCandidate,...scope,reference});
  assert.equal(unavailable.available,false);assert.equal(unavailable.reason,'historical_diff_unavailable');
  assert.equal(unavailable.current_generation,3);assert.equal(JSON.stringify(unavailable).includes('tampered'),false);
});
