const D=window.cocsDiagnostics,P=window.diagnosticsSource,$=id=>document.getElementById(id),json=v=>JSON.stringify(v,null,2),show=(id,v)=>$(id).textContent=typeof v==='string'?v:json(v);
const tabs={provenance:'Source & branches',world:'World & navigation',vehicles:'Vehicle range',match:'Match debugger',bots:'Bot inspector',performance:'Performance',regressions:'Scenarios',release:'Release desk'};
for(const [id,title]of Object.entries(tabs)){const b=document.createElement('button');b.textContent=title;b.dataset.tab=id;b.onclick=()=>{for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==id;for(const x of $('labNav').children)x.setAttribute('aria-selected',String(x===b));};$('labNav').append(b);}
show('sourceBadge',P.branch+' @ '+P.commit.slice(0,12));show('provenanceResult',P);let remote=null,evidence=null,brief=null,measurement=null,baseline=null,trace=[],model=null,renderer=null,scene=null,camera=null,routeResult=null;
function download(name,data){const u=URL.createObjectURL(new Blob([json(data)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function invalidate(){brief=null;$('releaseExport').disabled=true;}
function provenance(){return {loaded:P,checkedRemote:remote,intendedBranch:$('targetBranch').value,expectedDraft:$('draftCommit').value,sourceMatchesDraft:$('draftCommit').value===P.commit,branchMatches:$('targetBranch').value===P.branch};}
for(const id of ['targetBranch','draftCommit','releaseTitle'])$(id).oninput=()=>{invalidate();const p=provenance();show('mismatch',!p.branchMatches?'BRANCH MISMATCH — loaded engine and intended PR differ.':!p.sourceMatchesDraft?'Draft commit not verified against loaded engine.':'Loaded commit matches entered draft commit (manual assertion, not server verification).');};
$('branch').oninput=()=>{remote=null;invalidate();show('provenanceResult',P);};
$('resolve').onclick=async()=>{remote=null;invalidate();const branch=$('branch').value.trim();show('provenanceResult','Checking GitHub…');try{const r=await fetch('https://api.github.com/repos/mojomast/cocs/commits/'+encodeURIComponent(branch),{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error('GitHub HTTP '+r.status);const d=await r.json();if(!/^[a-f0-9]{40}$/.test(d.sha))throw Error('Invalid commit response');if(branch!==$('branch').value.trim())return;remote={branch,commit:d.sha,checkedAt:new Date().toISOString()};show('provenanceResult',{loaded:P,remote,status:d.sha===P.commit?'Up to date for checked branch':'DIFFERENT COMMIT — this running snapshot was NOT updated'});}catch(e){show('provenanceResult','Check failed; running snapshot unchanged: '+e.message);}};
let match=D.create();
const canvas=$('map'),ctx=canvas.getContext('2d');let nextFrom=true;
function bounds(){const n=match.nav;return {minX:Math.min(...n.map(n=>n.x))-4,maxX:Math.max(...n.map(n=>n.x))+4,minZ:Math.min(...n.map(n=>n.z))-4,maxZ:Math.max(...n.map(n=>n.z))+4};}
function xy(n){const b=bounds();return [(n.x-b.minX)/(b.maxX-b.minX)*canvas.width,(n.z-b.minZ)/(b.maxZ-b.minZ)*canvas.height];}
function line(a,b,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(...xy(a));ctx.lineTo(...xy(b));ctx.stroke();}
function drawMap(){ctx.clearRect(0,0,canvas.width,canvas.height);match.edges.forEach((es,i)=>es.forEach(j=>line(match.nav[i],match.nav[j],'#30485a')));match.nav.forEach((n,i)=>{const [x,y]=xy(n);ctx.fillStyle='#84bebd';ctx.fillRect(x-2,y-2,4,4);});for(const n of match.objectiveState?.nodes||[]){const [x,y]=xy(n);ctx.fillStyle='#eaa068';ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();ctx.fillText(n.id,x+9,y);}for(const s of routeResult?.segments||[])line(match.nav[s.from],match.nav[s.to],s.walkable?'#c9f36d':'#ff677c',4);}
for(const id of ['fromNode','toNode']){$(id).replaceChildren(...match.nav.map((n,i)=>new Option(`${i}: ${n.x.toFixed(1)}, ${n.y?.toFixed(1)}, ${n.z.toFixed(1)}`,i)));$(id).onchange=()=>{routeResult=null;drawMap();show('routeResult','Endpoints changed; run probe.');};}
$('toNode').selectedIndex=Math.max(0,match.nav.length-1);
$('route').onclick=()=>{try{routeResult=D.route(match,+$('fromNode').value,+$('toNode').value);show('routeResult',routeResult);drawMap();}catch(e){show('routeResult',e.message);}};
canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;let best=0,dist=Infinity;match.nav.forEach((n,i)=>{const p=xy(n),d=Math.hypot(p[0]-x,p[1]-y);if(d<dist){best=i;dist=d;}});const endpoint=$(nextFrom?'fromNode':'toNode');endpoint.value=best;endpoint.dispatchEvent(new Event('change'));nextFrom=!nextFrom;$('route').click();};drawMap();
function refresh(){const s=D.snapshot(match);show('matchResult',s);const old=$('bot').value;$('bot').replaceChildren(...s.actors.filter(a=>a.bot).map(a=>new Option('Bot '+a.id,a.id)));if([...$('bot').options].some(o=>o.value===old))$('bot').value=old;bot();}
function bot(){const a=D.snapshot(match).actors.find(a=>String(a.id)===$('bot').value);show('botResult',a?{...a,diagnostic:a.bot.route?.length?'Route present; inspect route index and target below':'No current route; this alone does not prove a stuck bot'}:'No bot present in this snapshot');}
$('bot').onchange=bot;
function step(){const before=D.snapshot(match);for(let i=0;i<60;i++)match.step(1/60);const after=D.snapshot(match);trace.push({from:before.time,to:after.time,objectiveChanged:json(before.objective)!==json(after.objective),before:before.objective,after:after.objective,actors:after.actors});if(trace.length>120)trace.shift();$('event').replaceChildren(...trace.map((t,i)=>new Option(`${t.to.toFixed(2)}s — objective ${t.objectiveChanged?'changed':'unchanged'}`,i)));$('event').value=trace.length-1;$('event').onchange();refresh();}
$('event').onchange=()=>show('eventResult',trace[+$('event').value]||'No recorded steps');$('stepMatch').onclick=$('stepBots').onclick=step;
$('resetMatch').onclick=()=>{match=D.create($('mode').value);trace=[];$('event').replaceChildren();show('eventResult','Match reset');refresh();drawMap();};$('mode').onchange=$('resetMatch').onclick;
$('exportTrace').onclick=()=>download('cocs-match-trace.json',{schema:'cocs.trace/v1',source:P,mode:$('mode').value,seed:12345,trace});
$('matchSource').href=`https://github.com/mojomast/cocs/blob/${P.commit}/game/cocs.mjs`;$('botSource').href=`https://github.com/mojomast/cocs/blob/${P.commit}/game/bots.mjs`;refresh();
function renderVehicle(){if(!renderer||!model)return;const u=model.userData;if(u.turret?.rotation)u.turret.rotation.y=+$('turret').value*Math.PI/180;for(const w of u.wheels||[])if(w.rotation)w.rotation.x=+$('wheels').value*Math.PI/180;renderer.render(scene,camera);}
$('turret').oninput=$('wheels').oninput=renderVehicle;
$('loadVehicle').onclick=()=>{try{const T=D.T;if(!renderer){renderer=new T.WebGLRenderer({canvas:$('vehicleCanvas'),antialias:true});renderer.setSize(900,500,false);scene=new T.Scene();scene.background=new T.Color('#182430');scene.add(new T.HemisphereLight(0xffffff,0x445566,3));const light=new T.DirectionalLight(0xffffff,3);light.position.set(5,9,8);scene.add(light);camera=new T.PerspectiveCamera(45,1.8,.01,1000);}if(model){scene.remove(model);D.dispose(model);}const probe=D.probeVehicle($('vehicle').value);model=probe.model;scene.add(model);const box=new T.Box3().setFromObject(model),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()).length();camera.position.copy(center).add(new T.Vector3(size*.8,size*.6,size));camera.lookAt(center);$('turret').value=$('wheels').value=0;renderVehicle();show('vehicleResult',{...probe.report,renderCounters:renderer.info.render});}catch(e){show('vehicleResult','Model probe failed: '+e.message);}};
$('benchmark').onclick=()=>{const m=D.create(),samples=[];for(let i=0;i<30;i++)m.step(1/60);for(let i=0;i<120;i++){const t=performance.now();m.step(1/60);samples.push(performance.now()-t);}samples.sort((a,b)=>a-b);measurement={source:P,mode:'cocs',seed:12345,steps:120,meanMs:samples.reduce((a,b)=>a+b,0)/samples.length,p95Ms:samples[Math.floor(samples.length*.95)],maxMs:samples.at(-1),scope:'Browser CPU simulation timing; not rendering, GPU or total frame time'};show('performanceResult',{measurement,baseline,meanChangePercent:baseline&&baseline.meanMs>0?(measurement.meanMs/baseline.meanMs-1)*100:null,vehicleRenderCounters:renderer?.info.render??'unavailable — load a vehicle'});$('saveBaseline').disabled=false;invalidate();};$('saveBaseline').onclick=()=>{baseline=measurement;show('performanceResult',{baseline,note:'Run again to compare. Timing depends on browser load.'});};
$('runSuite').onclick=()=>{const results=[];function run(name,fn){try{results.push({name,status:'pass',detail:fn()});}catch(e){results.push({name,status:'fail',error:e.message});}}run('Seeded engine replay',()=>{const a=D.create(),b=D.create();for(let i=0;i<60;i++){a.step(1/60);b.step(1/60);}if(json(D.snapshot(a))!==json(D.snapshot(b)))throw Error('Snapshots diverged');return 'Two fresh seeded matches agree after 60 ticks';});run('Selected navigation endpoints',()=>{const m=D.create(),r=D.route(m,+$('fromNode').value,+$('toNode').value);if(!r.reachable||r.segments.some(s=>!s.walkable))throw Error('Unreachable route or failed walkEdge segment');return r;});for(const kind of ['titan','scout','transport'])run(kind+' attached references',()=>{const p=D.probeVehicle(kind);try{if(!p.report.meshes||Object.values(p.report.refs).includes('DETACHED'))throw Error('Empty model or detached reference');return p.report;}finally{D.dispose(p.model);}});evidence={schema:'cocs.diagnostics/v1',source:P,createdAt:new Date().toISOString(),results,limitations:['Single pinned baseline only; no candidate checkout tested','Map player traversal and vehicle clearance unverified','No live match feed','No gameplay PR approval']};show('suiteResult',evidence);$('exportEvidence').disabled=false;invalidate();};$('exportEvidence').onclick=()=>download('cocs-diagnostics.json',evidence);
$('releaseBrief').onclick=()=>{const p=provenance();brief={schema:'cocs.release-review/v1',title:$('releaseTitle').value,provenance:p,status:'REVIEW ONLY — NOT APPROVED',blockers:[...(!p.branchMatches?['Target branch mismatch']:[]),...(!p.sourceMatchesDraft?['Draft commit not matched']:[]),...(!evidence?['Diagnostics not run']:evidence.results.filter(r=>r.status!=='pass').map(r=>'Diagnostic failed: '+r.name)),'Candidate diff not inspected by this tool','Gameplay traversal and compatibility gates remain required','Explicit publication approval required in the relevant Workshop'],evidence,performance:measurement,traceSamples:trace.length};show('releaseResult',brief);$('releaseExport').disabled=false;};$('releaseExport').onclick=()=>download('cocs-release-review.json',brief);
