const $=s=>document.querySelector(s);
const tools=[['welcome','Overview'],['updates','Update COCS Studio'],['assets','Asset Workshop','https://kimi.tailec998.ts.net:10446/'],['graphics','Graphics Lab','https://kimi.tailec998.ts.net:10447/'],['lattice','Lattice Operations','https://kimi.tailec998.ts.net:10448/'],['balance','Balance & Loadouts','../cocs-dev-lab-7c8d91bd4fad33e05c91a9eb/index.html'],['engineering','Engineering Lab','./diagnostics.html'],['compare','JSON Compare'],['planner','Change Planner']];
const checks=['Baseline commit and target branch recorded','Activation and expiry tested','Death, respawn and mode transitions tested','Model userData and moving-part contracts preserved','Stationary geometry batching checked','Traversal/navigation verified if map changes','Deterministic mechanics regression run','Accessibility and performance reviewed','Diff inspected; explicit PR approval still required'];
for(const text of checks){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';label.append(input,document.createTextNode(text));$('#checks').append(label);}
function select(id){for(const section of document.querySelectorAll('main>section'))section.hidden=section.id!==id;for(const frame of document.querySelectorAll('iframe'))frame.hidden=frame.dataset.tool!==id;for(const button of document.querySelectorAll('nav button'))button.setAttribute('aria-selected',String(button.dataset.tool===id));const tool=tools.find(t=>t[0]===id);if(tool?.[2]&&!document.querySelector(`iframe[data-tool="${id}"]`)){const frame=document.createElement('iframe');frame.dataset.tool=id;frame.title=tool[1];frame.setAttribute('sandbox','allow-scripts allow-forms allow-modals allow-downloads');if(id==='balance'||id==='engineering'){fetch(tool[2]).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text();}).then(html=>{const base=new URL(tool[2],location.href);frame.srcdoc=html.replace('<head>','<head>') .replace('<meta charset="utf-8">',`<meta charset="utf-8"><base href="${base.href}">`);}).catch(()=>{frame.srcdoc='<p>Balance tool could not load. Check connectivity and reopen Studio.</p>';});}else frame.src=tool[2];$('#frames').append(frame);}}
for(const [id,name]of tools){const b=document.createElement('button');b.textContent=name;b.dataset.tool=id;b.onclick=()=>select(id);$('#nav').append(b);}select('welcome');
$('#search').oninput=e=>{for(const b of document.querySelectorAll('nav button'))b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase());};
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
let comparison=null,brief=null;
function compare(a,b,path='',out=[]){if(JSON.stringify(a)===JSON.stringify(b))return out;const obj=x=>x!==null&&typeof x==='object';if(obj(a)&&obj(b)&&Array.isArray(a)===Array.isArray(b)){for(const k of new Set([...Object.keys(a),...Object.keys(b)])){const p=path+'/'+k.replaceAll('~','~0').replaceAll('/','~1');if(!Object.hasOwn(a,k))out.push({op:'add',path:p,after:b[k]});else if(!Object.hasOwn(b,k))out.push({op:'remove',path:p,before:a[k]});else compare(a[k],b[k],p,out);}}else out.push({op:'replace',path,before:a,after:b});return out;}
$('#diff').onclick=()=>{try{comparison={schema:'cocs-studio-comparison/v1',changes:compare(JSON.parse($('#before').value),JSON.parse($('#after').value))};$('#diffResult').textContent=comparison.changes.length?JSON.stringify(comparison,null,2):'No structural differences.';$('#diffExport').disabled=false;}catch(e){comparison=null;$('#diffExport').disabled=true;$('#diffResult').textContent='Invalid JSON: '+e.message;}};
$('#diffExport').onclick=()=>download('cocs-comparison.json',JSON.stringify(comparison,null,2));
function project(){return{schema:'cocs-studio-project/v1',title:$('#title').value,discipline:$('#discipline').value,trigger:$('#trigger').value,behavior:$('#behavior').value,recipe:$('#recipe').value,checks:[...document.querySelectorAll('#checks input')].map(i=>i.checked)};}
$('#brief').onclick=()=>{try{const p=project();if(!p.title.trim()||!p.behavior.trim())throw Error('Enter a title and desired behavior.');const recipe=p.recipe.trim()?JSON.parse(p.recipe):null;brief=`COCS change brief: ${p.title}\nDiscipline: ${p.discipline}\nSituation: ${p.trigger}\nDesired behavior: ${p.behavior}\n\nRecipe/scenario:\n${JSON.stringify(recipe,null,2)}\n\nManually recorded checklist (not automated proof):\n${checks.map((s,i)=>`${p.checks[i]?'[reported checked]':'[pending]'} ${s}`).join('\n')}\n\nInspect the current source and baseline. For Lattice use feat/fieldwork-plan; verify the correct target for other tools. Preserve kind, vehicle, wheels, turret, guns and flashUntil contracts where applicable. Keep moving parts independently addressable; batch stationary geometry. Do not bypass validation gates. Map PRs require traversal validation. Produce an isolated draft, tests, diff and evidence. Ask for explicit approval before creating a PR; never auto-merge.\n`;$('#briefResult').textContent=brief;$('#briefExport').disabled=false;}catch(e){brief=null;$('#briefResult').textContent=e.message;$('#briefExport').disabled=true;}};
for(const e of document.querySelectorAll('#planner input:not([type=file]),#planner textarea,#planner select'))e.addEventListener('input',()=>{$('#briefExport').disabled=true;brief=null;$('#briefResult').textContent='Inputs changed. Generate a fresh brief.';});
$('#briefExport').onclick=()=>download('cocs-change-brief.txt',brief,'text/plain');
$('#projectExport').onclick=()=>download('cocs-studio-project.json',JSON.stringify(project(),null,2));
$('#projectImport').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('Project exceeds 1 MB limit');const p=JSON.parse(await f.text());if(p.schema!=='cocs-studio-project/v1'||!['title','discipline','trigger','behavior','recipe'].every(k=>typeof p[k]==='string')||!Array.isArray(p.checks)||p.checks.length!==checks.length||!p.checks.every(v=>typeof v==='boolean')||![...$('#discipline').options].some(o=>o.value===p.discipline))throw Error('Invalid project schema');for(const k of ['title','discipline','trigger','behavior','recipe'])$('#'+k).value=p[k];[...document.querySelectorAll('#checks input')].forEach((el,i)=>el.checked=p.checks[i]);brief=null;$('#briefExport').disabled=true;$('#briefResult').textContent='Project imported. Generate a fresh brief.';}catch(err){$('#briefResult').textContent='Import rejected: '+err.message;}finally{e.target.value='';}};
for(const id of ['before','after'])$('#'+id).oninput=()=>{comparison=null;$('#diffExport').disabled=true;$('#diffResult').textContent='Inputs changed. Run comparison again.';};
