const q=s=>document.querySelector(s);
const api='https://api.github.com/repos/mojomast/cocs';
let branches=[],report=null;
async function get(path){const r=await fetch(api+path,{headers:{Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`GitHub HTTP ${r.status}; source remains unchanged.`);return r.json();}
function invalidate(){report=null;q('#updateExport').disabled=true;}
q('#updateScan').onclick=async()=>{invalidate();q('#updateScan').disabled=true;q('#updateCompare').disabled=true;q('#updateBranches').replaceChildren();q('#updateStatus').textContent='Checking all branch tips…';try{branches=[];for(let page=1;;page++){const batch=await get(`/branches?per_page=100&page=${page}`);for(const b of batch){const c=await get('/commits/'+b.commit.sha);branches.push({name:b.name,commit:b.commit.sha,date:c.commit.committer.date,message:c.commit.message.split('\n')[0]});}if(batch.length<100)break;}branches.sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));const cutoff=Date.now()-Number(q('#updateDays').value)*86400000;for(const b of branches.filter(b=>Date.parse(b.date)>=cutoff)){const o=document.createElement('option');o.value=b.commit;o.textContent=`${b.name} · ${b.date.slice(0,10)} · ${b.commit.slice(0,8)} · ${b.message}`;o.dataset.branch=b.name;q('#updateBranches').append(o);}q('#updateCompare').disabled=!q('#updateBranches').options.length;q('#updateStatus').textContent=`Checked ${branches.length} branch tips; ${q('#updateBranches').options.length} within the selected window. Dates are tip commit dates, not push dates. Choose a branch; nothing has been updated.`;}catch(e){q('#updateStatus').textContent=e.message;}finally{q('#updateScan').disabled=false;}};
q('#updateDays').onchange=()=>{invalidate();q('#updateCompare').disabled=true;q('#updateStatus').textContent='Window changed. Scan again.';};
q('#updateBranches').onchange=()=>{invalidate();q('#updateStatus').textContent='Selection changed. Compare again.';};
q('#updateCompare').onclick=async()=>{invalidate();q('#updateCompare').disabled=true;q('#updateStatus').textContent='Comparing selected commit against bundled SDK source…';try{const option=q('#updateBranches').selectedOptions[0];const target=branches.find(b=>b.name===option.dataset.branch);const baseline=window.diagnosticsSource;const diff=await get(`/compare/${baseline.commit}...${target.commit}?per_page=100`);const files=diff.files||[];const impacts=files.map(f=>({path:f.filename,previousPath:f.previous_filename,status:f.status,additions:f.additions,deletions:f.deletions,patch:f.patch||null,checks:[f.filename,f.previous_filename||''].some(p=>/^game\/(core|bots|view|cocs)\.mjs$/.test(p))?['Review SDK diagnostics-adapter imports and runtime contracts','Rebuild pinned diagnostic engine','Run vehicle, navigation, seeded match and scenario browser tests']:['Review dependencies and tool coverage; path matching cannot prove compatibility']}));report={schema:'cocs.sdk-update-review/v1',createdAt:new Date().toISOString(),baseline,target,comparison:{status:diff.status,aheadBy:diff.ahead_by,behindBy:diff.behind_by,url:diff.html_url,filesMayBeTruncated:files.length>=300},impacts,activation:'NOT UPDATED — review only',requiredWorkflow:['Fetch chosen branch into isolated clean checkout; verify exact target SHA','Compare SDK adapter and all affected tool dependencies with source changes','Implement required adapter/tool changes; do not merely change provenance','Build candidate immutable Studio bundle and run SDK plus browser regression tests','Request activation confirmation; retain prior bundle for rollback'],limitations:['GitHub compare is merge-base based for diverged branches, not an exact tree diff','GitHub may omit patches and caps changed files at 300; trusted local git diff is required before rebuild','Existing remote Workshop, Graphics and Lattice services are not synchronized by this review']};q('#updateStatus').textContent=JSON.stringify(report,null,2);q('#updateExport').disabled=false;}catch(e){q('#updateStatus').textContent=e.message;}finally{q('#updateCompare').disabled=false;}};
q('#updateExport').onclick=()=>{if(!report)return;const u=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='cocs-sdk-update-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
