import {WEAPONS,CHARACTERS,HARNESSES,POWERUPS,RULES,validLoadout} from '../cocs-viewer/vendor/game/data.mjs';
import provenance from '../cocs-viewer/dist/provenance.json';
const $=s=>document.querySelector(s), fields=['damage','pellets','interval','range'];
const base=WEAPONS.map(w=>({...w,pellets:w.pellets||1}));let draft=base.map(w=>({...w}));
const fmt=n=>Number.isFinite(n)?Number(n.toFixed(3)).toString():'∞';
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function settings(){return {health:Number($('#health').value)||100,distance:Number($('#distance').value)||0,splash:$('#splash').checked};}
function metric(w){const s=settings();let scale=1;if(w.falloff&&s.distance>w.falloff.start)scale=1-(1-w.falloff.min)*Math.min(1,(s.distance-w.falloff.start)/(w.falloff.end-w.falloff.start));const shot=s.distance>w.range?0:w.damage*w.pellets*scale+(s.splash?(w.splash||0):0);const shots=shot>0?Math.ceil(s.health/shot):Infinity;return {shot,dps:shot/w.interval,shots,ttk:shots===Infinity?Infinity:Math.max(0,shots-1)*w.interval};}
function changes(){return draft.flatMap((w,i)=>fields.filter(k=>w[k]!==base[i][k]).map(k=>({weapon:i,name:w.name,field:k,before:base[i][k],after:w[k]})));}
function render(){const body=$('#weapons');body.replaceChildren();draft.forEach((w,i)=>{const tr=el('tr');tr.append(el('td',w.name));for(const k of fields){const td=el('td',undefined,w[k]!==base[i][k]?'changed':'');const input=el('input');input.type='number';input.value=w[k];input.min=k==='interval'?'0.01':'1';input.max=k==='interval'?'60':k==='pellets'?'100':'10000';input.step=k==='pellets'?'1':'any';input.setAttribute('aria-label',w.name+' '+k);input.onchange=()=>{const v=Number(input.value);if(!input.checkValidity()||!Number.isFinite(v)){input.value=w[k];return;}draft[i]={...w,[k]:v};render();};td.append(input);tr.append(td);}const m=metric(w),b=metric(base[i]);for(const v of [m.shot,m.dps,m.shots,m.ttk,m.dps-b.dps])tr.append(el('td',fmt(v)));body.append(tr);});const bars=$('#bars');bars.replaceChildren();const max=Math.max(1,...draft.map(w=>metric(w).dps));draft.forEach(w=>{const row=el('div',undefined,'bar'),track=el('div'),bar=el('i');bar.style.width=metric(w).dps/max*100+'%';track.append(bar);row.append(el('span',w.name),track,el('span',fmt(metric(w).dps)));bars.append(row);});$('#diff').textContent=changes().length?changes().map(c=>`${c.name} · ${c.field}: ${c.before} → ${c.after}`).join('\n'):'No tuning changes. Edit weapon values in Weapon balance.';}
function roster(){const c=CHARACTERS.find(c=>c.id===$('#character').value);$('#character-info').textContent=`${c.name} — Health ${c.stats.health} · Armor ${c.stats.armor} · Speed ${c.stats.speed}\n${c.detail}`;$('#harnesses').replaceChildren(...HARNESSES.map(h=>{const card=el('div',undefined,'card');const ok=validLoadout(c.id,h.id);card.append(el('h3',h.name),el('p',ok?'Compatible':'Not allowed for this character',ok?'good':'bad'),el('p',h.power+' · '+h.stat),el('p',`Cooldown ${h.cooldown}s · Duration ${h.duration}s`));return card;}));}
function download(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const proposal=()=>({schema:'cocs-tuning-v1',repository:provenance.repository,commit:provenance.commit,changes:changes(),assumptions:settings()});
$('#provenance').textContent='Repository data snapshot · '+provenance.commit.slice(0,12)+' · Session-only tuning, export to keep your work';
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));});
for(const id of ['health','distance','splash'])$('#'+id).oninput=render;
$('#character').append(...CHARACTERS.map(c=>{const o=el('option',c.name);o.value=c.id;return o;}));$('#character').onchange=roster;
$('#powerups').append(...POWERUPS.map(p=>{const c=el('div',undefined,'card');c.append(el('h3',p.name),el('p',p.duration+' seconds'),el('pre',JSON.stringify(p.effect,null,2)));return c;}));$('#rules').textContent=JSON.stringify(RULES,null,2);
$('#export').onclick=()=>download('cocs-tuning.json',JSON.stringify(proposal(),null,2),'application/json');
$('#brief').onclick=()=>download('cocs-change-brief.txt',`Implement the following COCS weapon tuning proposal in ${provenance.repository}.\nBaseline commit: ${provenance.commit}. Check upstream changes before applying. Preserve unrelated work. Inspect game/data.mjs, review dependent combat mechanics, run relevant tests and provide a diff. Do not push or open a PR without approval. These idealized estimates do not establish gameplay balance.\n\n${JSON.stringify(proposal(),null,2)}`);
$('#csv').onclick=()=>download('cocs-balance.csv','weapon,damage,pellets,interval,range,effective_shot,dps,shots,ttk,delta_dps\n'+draft.map((w,i)=>{const m=metric(w);return [JSON.stringify(w.name),...fields.map(k=>w[k]),m.shot,m.dps,m.shots,m.ttk,m.dps-metric(base[i]).dps].join(',');}).join('\n'),'text/csv');
$('#reset').onclick=()=>{if(confirm('Discard all tuning changes?')){draft=base.map(w=>({...w}));render();$('#message').textContent='Tuning reset.';}};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('File too large');const p=JSON.parse(await file.text());if(p.schema!=='cocs-tuning-v1'||p.commit!==provenance.commit||p.repository!==provenance.repository||!Array.isArray(p.changes)||p.changes.length>40)throw Error('Unsupported proposal or mismatched baseline');const next=base.map(w=>({...w})),seen=new Set();for(const c of p.changes){const key=c.weapon+':'+c.field;if(!Number.isInteger(c.weapon)||!base[c.weapon]||!fields.includes(c.field)||c.before!==base[c.weapon][c.field]||seen.has(key)||typeof c.after!=='number'||!Number.isFinite(c.after)||c.after<(c.field==='interval'?.01:1)||c.after>(c.field==='interval'?60:c.field==='pellets'?100:10000)||(c.field==='pellets'&&!Number.isInteger(c.after)))throw Error('Invalid or duplicate change');seen.add(key);next[c.weapon][c.field]=c.after;}draft=next;render();$('#message').textContent='Imported '+p.changes.length+' changes. Simulation settings remain unchanged.';}catch(err){$('#message').textContent='Import rejected: '+err.message;}finally{e.target.value='';}};
render();roster();document.querySelector('[data-tab]').click();
