import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ArenaView,weaponModel,legacyWeaponModel,robotModel,vehicleModel} from './vendor/game/view.mjs';
import {MAPS} from './vendor/game/maps.mjs';
import {CHARACTERS,WEAPONS} from './vendor/game/data.mjs';
import {VEHICLE_TYPES} from './vendor/game/vehicles.mjs';
import {TEXTURE_KINDS,surfaceTextures,clearSurfaceTextures} from './vendor/game/textures.mjs';
import {arenaMeta} from './vendor/game/arenas.mjs';
const $=id=>document.getElementById(id);
const catalog=[...MAPS.map((data,i)=>({id:'map:'+data.id,kind:'Maps',name:data.name,data,i,source:'game/maps.mjs → ArenaView.buildArena',tag:arenaMeta(data)?.group})),...CHARACTERS.map((data,i)=>({id:'character:'+data.id,kind:'Characters',name:data.name,data,i,source:'game/view.mjs → robotModel',tag:data.tag})),...WEAPONS.map((data,i)=>({id:'weapon:'+i,kind:'Weapons',name:data.name,data,i,source:'game/view.mjs → weaponModel',tag:'Current model'})),...VEHICLE_TYPES.map((data,i)=>({id:'vehicle:'+data.id,kind:'Vehicles',name:data.name||data.id,data,i,source:'game/view.mjs → vehicleModel',tag:data.id})),...TEXTURE_KINDS.map((name,i)=>({id:'material:'+name,kind:'Materials',name:name.replaceAll('_',' '),data:{id:name},i,source:'game/textures.mjs → surfaceTextures',tag:'Sphere + cube swatches'})),...WEAPONS.map((data,i)=>({id:'legacy:'+i,kind:'Legacy',name:data.name+' · legacy',data,i,source:'game/view.mjs → legacyWeaponModel',tag:'Legacy weapon geometry'}))];
let view,renderer,controls,camera,studio,root,activeScene,current,category='All',busy=false,radius=3,helper,frames=0,last=performance.now(),loadSeq=0,mapFog,mapBackground,selectedBounds;
const keys=new Set();
const info={ready:false,errors:[],catalog:catalog.map(({id,kind,name})=>({id,kind,name})),selected:null,meshes:0,triangles:0,frames:0};
window.cocsViewer=info;
function fail(e){console.error(e);info.errors.push(String(e));$('loading').hidden=true;$('status').textContent='Could not load asset: '+e.message;busy=false;}
window.addEventListener('error',e=>{info.errors.push(e.message);$('status').textContent='Viewer error: '+e.message;$('loading').hidden=true;});
$('revision').textContent=SOURCE_COMMIT.slice(0,8);
function list(){const q=$('search').value.toLowerCase().trim(),entries=catalog.filter(e=>(category==='All'||e.kind===category)&&(`${e.name} ${e.id} ${e.tag||''}`).toLowerCase().includes(q));$('count').textContent=`${entries.length} / ${catalog.length} ASSETS`;$('list').replaceChildren();for(const e of entries){const b=document.createElement('button');b.dataset.asset=e.id;b.classList.toggle('active',current?.id===e.id);const title=document.createElement('div');title.textContent=e.name;const sub=document.createElement('small');sub.textContent=`${e.kind.toUpperCase()} · ${e.tag||e.data.id||''}`;b.append(title,sub);b.onclick=()=>select(e);$('list').append(b);}if(!entries.length)$('list').textContent='No matching assets.';}
for(const cat of ['All','Maps','Characters','Weapons','Vehicles','Materials','Legacy']){const b=document.createElement('button');b.textContent=cat;b.dataset.category=cat;b.classList.toggle('active',cat===category);b.onclick=()=>{category=cat;for(const x of $('categories').children)x.classList.toggle('active',x===b);list();};$('categories').append(b);}
$('search').oninput=list;
$('sidebar').onclick=()=>document.body.classList.toggle('library-hidden');
$('detailsToggle').onclick=()=>{$('details').hidden=!$('details').hidden;};
function disposeTree(object){if(!object)return;const geos=new Set(),mats=new Set(),texs=new Set();object.traverse(n=>{if(n.geometry)geos.add(n.geometry);for(const m of n.material?(Array.isArray(n.material)?n.material:[n.material]):[]){mats.add(m);for(const v of Object.values(m))if(v?.isTexture)texs.add(v);}});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());texs.forEach(t=>t.dispose());object.removeFromParent();}
function boundsFor(){if(current?.kind==='Maps'){const b=current.data.bounds||{minX:-14,maxX:14,minZ:-14,maxZ:14};return new T.Box3(new T.Vector3(b.minX,-2,b.minZ),new T.Vector3(b.maxX,12,b.maxZ));}return new T.Box3().setFromObject(root);}
function fit(direction=new T.Vector3(1,.65,1)){const box=boundsFor();if(box.isEmpty())return;selectedBounds=box;const center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());radius=Math.max(size.length()/2,.1);const distance=radius/Math.sin(T.MathUtils.degToRad(camera.fov/2))/Math.min(1,camera.aspect)*1.1;camera.position.copy(center).addScaledVector(direction.normalize(),distance);camera.near=Math.max(.005,radius/3000);camera.far=Math.max(1000,radius*40);camera.updateProjectionMatrix();controls.target.copy(center);controls.minDistance=radius*.002;controls.maxDistance=radius*30;controls.update();}
function settings(){if(!current)return;root?.traverse(n=>{for(const m of n.material?(Array.isArray(n.material)?n.material:[n.material]):[])if('wireframe'in m)m.wireframe=$('wire').checked;if(n.userData.ceiling!==undefined)n.visible=$('roof').checked;});if(helper)helper.visible=$('grid').checked;if(current.kind==='Maps'){view.scene.fog=$('sky').checked?mapFog:null;view.scene.background=$('sky').checked?mapBackground:new T.Color('#111c28');if(view.sky)view.sky.visible=$('sky').checked;if(view.mountains)view.mountains.visible=$('sky').checked;}controls.autoRotate=$('rotate').checked;renderer.toneMappingExposure=+$('exposure').value;}
async function select(entry){const seq=++loadSeq;busy=true;$('loading').hidden=false;$('loading').textContent='Building '+entry.name+'…';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));if(seq!==loadSeq)return;try{
 if(root&&current?.kind!=='Maps')disposeTree(root);if(helper){disposeTree(helper);helper=null;}root=null;
 current=entry;info.selected=entry.id;info.ready=false;list();
 if(entry.kind==='Maps'){
  // Use the repository's authored world renderer, not reconstructed proxy boxes.
  view.arenaAssets?.dispose();view.arenaAssets=null;view.buildArena(entry.data);
  root=view.worldGroup;activeScene=view.scene;mapFog=activeScene.fog||new T.FogExp2(entry.data.background,.008);mapBackground=new T.Color(entry.data.background);view.camera.visible=false;
 }else{
  activeScene=studio;clearSurfaceTextures();
  if(entry.kind==='Characters')root=robotModel(entry.data.id);
  else if(entry.kind==='Weapons')root=weaponModel(entry.i);
  else if(entry.kind==='Legacy')root=legacyWeaponModel(entry.i);
  else if(entry.kind==='Vehicles')root=vehicleModel(entry.data.id);
  else{root=new T.Group();const tex=surfaceTextures(entry.data.id,{size:256,seed:17,repeat:[2,2]});const mat=new T.MeshStandardMaterial({map:tex?.map,normalMap:tex?.normalMap,roughnessMap:tex?.roughnessMap,metalness:.15,roughness:.7});const sphere=new T.Mesh(new T.SphereGeometry(1,48,32),mat);sphere.position.set(-1.3,1.15,0);const cube=new T.Mesh(new T.BoxGeometry(1.5,1.5,1.5),mat);cube.position.set(1.3,.9,0);root.add(sphere,cube);}
  studio.add(root);
 }
 const box=boundsFor(),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());const span=Math.max(size.x,size.z,1)*1.6;helper=new T.GridHelper(span,20,'#4f7068','#253640');helper.position.set(center.x,entry.kind==='Maps'?-0.04:box.min.y-.02,center.z);activeScene.add(helper);
 let meshes=0,triangles=0;root.traverse(n=>{if(n.isMesh){meshes++;triangles+=(n.geometry.index?.count||n.geometry.attributes.position?.count||0)/3;}});info.meshes=meshes;info.triangles=Math.round(triangles);
 $('kind').textContent=entry.kind.toUpperCase()+' / '+(entry.tag||'PROCEDURAL');$('title').textContent=entry.name;$('description').textContent=entry.data.description||entry.data.detail||(entry.kind==='Maps'?'Explore the authored world. Zoom into structures or use WASD to move through the map.':'Original game model • interactive 3D inspection');
 const metadata=entry.kind==='Maps'?{id:entry.data.id,bounds:entry.data.bounds,biome:entry.data.biome,blocks:entry.data.blocks?.length,platforms:entry.data.platforms?.length,terrain:!!entry.data.terrain,structures:entry.data.structures?.length,...arenaMeta(entry.data)}:entry.data;
 $('metadata').textContent=JSON.stringify({source:entry.source,commit:SOURCE_COMMIT,meshes,triangles:info.triangles,asset:metadata},(k,v)=>typeof v==='number'&&!Number.isFinite(v)?String(v):v,2);
 fit();settings();$('loading').hidden=true;$('status').textContent=`${entry.kind} / ${entry.name} · ${meshes.toLocaleString()} meshes · ${info.triangles.toLocaleString()} triangles`;busy=false;info.ready=true;parent.postMessage({type:'cocs-selected',asset:entry.id,name:entry.name,commit:SOURCE_COMMIT},'*');
 }catch(e){fail(e);}}
$('fit').onclick=()=>fit();$('top').onclick=()=>fit(new T.Vector3(0,1,.0001));$('front').onclick=()=>fit(new T.Vector3(0,.12,1));$('side').onclick=()=>fit(new T.Vector3(1,.12,0));for(const id of ['wire','rotate','grid','sky','roof','exposure'])$(id).oninput=settings;
$('viewport').addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight','KeyF'].includes(e.code)){e.preventDefault();keys.add(e.code);if(e.code==='KeyF')fit();}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());$('viewport').addEventListener('focusout',()=>keys.clear());$('canvas').addEventListener('pointerdown',()=>$('viewport').focus());
$('canvas').addEventListener('dblclick',e=>{const rect=$('canvas').getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObject(root,true).find(h=>h.object.visible&&!h.object.userData.sky);if(hit){controls.target.copy(hit.point);controls.update();$('status').textContent='Focused surface · F restores full asset';}});
function render(now){requestAnimationFrame(render);if(!renderer||!activeScene)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(!busy&&keys.size){const forward=new T.Vector3();camera.getWorldDirection(forward);const right=new T.Vector3().crossVectors(forward,camera.up).normalize(),move=new T.Vector3();if(keys.has('KeyW'))move.add(forward);if(keys.has('KeyS'))move.sub(forward);if(keys.has('KeyD'))move.add(right);if(keys.has('KeyA'))move.sub(right);if(keys.has('KeyE'))move.y+=1;if(keys.has('KeyQ'))move.y-=1;move.multiplyScalar(Math.max(.5,radius*.28)*dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?4:1));camera.position.add(move);controls.target.add(move);}controls.update();renderer.info.reset();renderer.render(activeScene,camera);info.frames++;if(++frames%30===0)$('stats').textContent=`${renderer.info.render.calls} DRAW CALLS\n${renderer.info.render.triangles.toLocaleString()} VISIBLE TRIANGLES`;}
async function init(){list();view=new ArenaView($('canvas'));renderer=view.renderer;if(!renderer.isWebGLRenderer)throw Error('WebGL 2 is required for this asset inspector. Enable browser hardware acceleration.');renderer.shadowMap.enabled=false;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));camera=new T.PerspectiveCamera(45,1,.01,5000);controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.dampingFactor=.09;controls.autoRotateSpeed=.7;studio=new T.Scene();studio.background=new T.Color('#111c28');studio.environment=view.scene.environment;studio.add(new T.HemisphereLight('#d8efff','#455168',3));for(const [color,intensity,pos]of [['#ffffff',3,[5,8,5]],['#a5ceff',2,[-5,3,-5]],['#c5ffae',1,[0,4,5]]]){const l=new T.DirectionalLight(color,intensity);l.position.set(...pos);studio.add(l);}const resize=()=>{const r=$('viewport').getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix();};new ResizeObserver(resize).observe($('viewport'));resize();info.select=id=>{const e=catalog.find(e=>e.id===id);if(!e)throw Error('Unknown asset '+id);return select(e);};info.inspect=()=>({camera:camera.position.toArray(),target:controls.target.toArray(),wireframe:$('wire').checked,canvas:[renderer.domElement.width,renderer.domElement.height],selected:info.selected,meshes:info.meshes,triangles:info.triangles});requestAnimationFrame(render);await select(catalog.find(e=>e.id===(window.__initialAsset||'vehicle:puma'))||catalog[0]);}
init().then(()=>{if(!info.ready)throw Error(info.errors.join('; ')||'Asset initialization failed');requestAnimationFrame(()=>requestAnimationFrame(()=>parent.postMessage({type:'cocs-ready',commit:SOURCE_COMMIT},'*')));}).catch(e=>{fail(e);parent.postMessage({type:'cocs-ready',error:String(e)},'*');});
