'use strict';
const $=id=>document.getElementById(id);let selected=null,jobs=[],busy=false,submitting=false,timer,signature='';
async function api(path,options){const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function values(id,integer){const raw=$(id).value.split(',').map(v=>v.trim());if(raw.some(v=>!v))throw new Error('Empty comparison value.');const a=[...new Set(raw.map(Number))];if(a.length>8||a.some(v=>!Number.isFinite(v)||v<1||v>(integer?100:10)||(integer&&!Number.isInteger(v))))throw new Error(integer?'Steps: 1–8 integers from 1 to 100.':'Guidance: 1–8 values from 1 to 10.');return a;}
function plan(){const count=$('fixed').checked?1:Number($('count').value),compare=$('compare').checked;const steps=compare?values('stepValues',true):[Number($('steps').value)],guidance=compare?values('guidanceValues',false):[Number($('cfg').value)];if(!Number.isInteger(count)||count<1||count>32)throw new Error('Choose 1–32 random seeds.');const total=count*steps.length*guidance.length;if(total>128)throw new Error('Reduce settings or seeds to at most 128 images.');return {count,steps,guidance,total};}
function controls(){if($('compare').checked){$('fixed').checked=false;}$('fixed').disabled=$('compare').checked;$('seedControls').hidden=!$('fixed').checked;$('count').disabled=$('fixed').checked;$('singleSettings').hidden=$('compare').checked;$('sweepSettings').hidden=!$('compare').checked;try{const p=plan();$('estimate').textContent=`${p.total} images · ${p.count} seed${p.count===1?'':'s'} × ${p.steps.length} steps × ${p.guidance.length} guidance`;$('generate').disabled=busy||submitting;}catch(e){$('estimate').textContent=e.message;$('generate').disabled=true;}}
function show(job){selected=job;const img=document.createElement('img');img.src=job.image;img.alt=job.prompt;$('preview').replaceChildren(img);$('meta').textContent=`${job.prompt}\n\nSeed ${job.seed}\n${job.steps} steps · guidance ${job.cfg}\n${job.seconds}s total · ${job.warm?'warm reuse':'cold load'}\n${job.threads} CPU threads · 256 × 256`;$('download').href=job.image;if(!$('detail').open)$('detail').showModal();signature='';render();}
function render(){let shown=jobs.slice();if($('filter').value==='latest')shown=shown.filter(j=>j.batch===jobs[0]?.batch);if($('sort').value==='compare')shown.sort((a,b)=>a.seed-b.seed||a.steps-b.steps||a.cfg-b.cfg);const sig=JSON.stringify([shown,selected?.id]);if(sig===signature)return;signature=sig;$('empty').hidden=shown.length>0;$('total').textContent=`${shown.filter(j=>j.status==='done').length} / ${shown.length}`;$('history').replaceChildren(...shown.map(j=>{const card=document.createElement('article');card.className='card'+(selected?.id===j.id?' selected':'');const button=document.createElement('button');button.disabled=j.status!=='done';button.setAttribute('aria-label',`Inspect seed ${j.seed}, ${j.steps} steps, guidance ${j.cfg}`);if(j.status==='done'){const img=document.createElement('img');img.src=j.image;img.alt=j.prompt;img.loading='lazy';button.append(img);button.onclick=()=>show(j);}else button.textContent=j.status==='running'?'Rendering…':j.status;const caption=document.createElement('div');caption.className='caption';const title=document.createElement('strong');title.textContent=`${j.steps} steps · G ${j.cfg}`;const seed=document.createElement('span');seed.textContent=`Seed ${j.seed}`;const state=document.createElement('span');state.textContent=j.status==='done'?`${j.seconds}s · ${j.warm?'warm':'cold'}`:j.error||j.status;caption.append(title,seed,state);if(j.status==='done'){const a=document.createElement('a');a.href=j.image;a.target='_blank';a.rel='noopener';a.textContent='Open PNG ↗';caption.append(a);}card.append(button,caption);return card;}));}
async function refresh(){clearTimeout(timer);try{const d=await api('/api/status');jobs=d.jobs;busy=d.busy;$('badge').textContent=`CPU · ${busy?'generating':d.worker?.loaded?'warm':'idle'} · ${d.worker?.threads||16} threads`;const batch=jobs.filter(j=>j.batch===jobs[0]?.batch);const complete=batch.filter(j=>!['queued','running'].includes(j.status)).length,queued=batch.filter(j=>j.status==='queued').length,failed=batch.filter(j=>j.status==='failed').length,cancelled=batch.filter(j=>j.status==='cancelled').length;$('progress').max=batch.length||1;$('progress').value=complete;$('cancel').disabled=!queued;const running=batch.find(j=>j.status==='running');$('status').textContent=batch.length?`${complete} / ${batch.length} finished · ${queued} queued${failed?` · ${failed} failed`:''}${cancelled?` · ${cancelled} cancelled`:''}${running?`\nRendering ${running.steps} steps / G ${running.cfg} · ${Math.max(0,Math.floor(Date.now()/1000-(running.started||running.created)))}s`:''}`:'Ready to generate.';controls();render();}catch(e){$('badge').textContent='Disconnected';$('generate').disabled=true;$('status').textContent=e.message;}finally{timer=setTimeout(refresh,1500);}}
$('form').oninput=controls;$('filter').onchange=render;$('sort').onchange=render;$('size').oninput=()=>document.documentElement.style.setProperty('--tile',$('size').value+'px');$('detailClose').onclick=()=>$('detail').close();$('random').onclick=()=>{$('seed').value=crypto.getRandomValues(new Uint32Array(1))[0]%2147483648;};
$('reuse').onclick=()=>{if(!selected)return;$('prompt').value=selected.prompt;$('compare').checked=false;$('fixed').checked=true;$('seed').value=selected.seed;$('steps').value=selected.steps;$('cfg').value=selected.cfg;controls();$('detail').close();};
$('cancel').onclick=async()=>{try{await post('/api/cancel',{});await refresh();}catch(e){$('error').textContent=e.message;}};
$('form').onsubmit=async e=>{e.preventDefault();submitting=true;$('generate').disabled=true;$('error').textContent='';try{const p=plan();await post($('fixed').checked?'/api/generate':'/api/batch',$('fixed').checked?{prompt:$('prompt').value,seed:Number($('seed').value),steps:p.steps[0],cfg:p.guidance[0]}:{prompt:$('prompt').value,count:p.count,steps:p.steps,guidance:p.guidance});$('filter').value='latest';}catch(e){$('error').textContent=e.message;}finally{submitting=false;await refresh();}};
controls();refresh();
