// Private owner API. Deliberately separate from workspace layout v1.
const id={type:'string',pattern:'^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$'};
const text=(maxLength)=>({type:'string',minLength:1,maxLength});
const object=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
export const WORKBENCH_VERSION=1;
export const workbenchRequests={
  list:object({action:{const:'list'},workspace_id:id}),
  register_preview:{...object({action:{const:'register_preview'},workspace_id:id,root:text(4096),name:text(120),git_mapping:object({git_directory:text(4096),common_directory:text(4096)})}),required:['action','workspace_id','root','name']},
  register_commit:object({action:{const:'register_commit'},workspace_id:id,approval_id:id}),
  inspect:object({action:{const:'inspect'},workspace_id:id,project_id:id}),
  revoke_project:object({action:{const:'revoke_project'},workspace_id:id,project_id:id,base_generation:{type:'integer',minimum:1}}),
  file:object({action:{const:'file'},workspace_id:id,project_id:id,resource_id:id}),
  bind:object({action:{const:'bind'},workspace_id:id,project_id:id,resource_id:id,pane_id:id,base_revision:{type:'integer',minimum:1},role:{enum:['project_files','primary_agent','active_terminal','preview','candidate_diff','job_output']}}),
  unbind:object({action:{const:'unbind'},workspace_id:id,project_id:id,binding_id:id}),
  link_pane:object({action:{const:'link_pane'},workspace_id:id,project_id:id,pane_id:id,base_revision:{type:'integer',minimum:1}}),
  doctor:object({action:{const:'doctor'},workspace_id:id}),
};
export const workbenchSchema={ $schema:'http://json-schema.org/draft-07/schema#',title:'Comet Project Workbench owner requests v1',oneOf:Object.values(workbenchRequests)};
export const workbenchTypes=`// Generated by scripts/generate-workbench-contract.mjs; do not edit.
export type WorkbenchRequest =
 | {action:'list'|'doctor';workspace_id:string}
 | {action:'register_preview';workspace_id:string;root:string;name:string;git_mapping?:{git_directory:string;common_directory:string}}
 | {action:'register_commit';workspace_id:string;approval_id:string}
 | {action:'inspect';workspace_id:string;project_id:string}
 | {action:'revoke_project';workspace_id:string;project_id:string;base_generation:number}
 | {action:'file';workspace_id:string;project_id:string;resource_id:string}
 | {action:'link_pane';workspace_id:string;project_id:string;pane_id:string;base_revision:number}
 | {action:'unbind';workspace_id:string;project_id:string;binding_id:string}
 | {action:'bind';workspace_id:string;project_id:string;resource_id:string;pane_id:string;base_revision:number;role:'project_files'|'primary_agent'|'active_terminal'|'preview'|'candidate_diff'|'job_output'};
export type Project = {version:1;id:string;workspace_id:string;name:string;root:string;generation:number;created_at:number;active?:boolean};
export type Resource = {version:1;id:string;project_id:string;kind:'file'|'terminal'|'conversation'|'browser';path?:string;pane_id?:string;generation:number;hash?:string;bytes?:number;state:string};
export type FileSnapshot = {id:string;resource_id:string;hash:string;captured_at:number;text:string;binary:boolean;bytes:number;lines:number;truncated:boolean;stale:boolean;generation:number};
`;
