'use strict';
const D=window.Devplan,$=s=>document.querySelector(s),steps=['Interview','Complexity','Design draft','Review & correct','Development plan','Checkpoints','Export & handoff'];
let state={version:1,answers:{},spec:'',step:0,question:0,approved:false,checkpoints:[]},selected='spec.md',storage=false;
try{const raw=localStorage.getItem('orbit-devplan-v1');if(raw){const saved=JSON.parse(raw);state={...D.parseProject(saved),checkpoints:Array.isArray(saved.checkpoints)?saved.checkpoints.slice(-12):[]};}storage=true;}catch{}
$('#storage').textContent=storage?'Draft autosaves in this browser. Export a project backup before upgrades.':'Sandbox mode: memory only. Export project before closing or reloading.';
function el(tag,text,cls){let e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls){let e=el('button',text,cls);e.onclick=fn;return e;}
function persist(){if(storage)try{localStorage.setItem('orbit-devplan-v1',JSON.stringify(state));}catch{storage=false;$('#storage').textContent='Autosave unavailable. Export your project now.';}}
function note(t){$('#notice').textContent=t;}
function heading(k,t,desc){const v=$('#view');v.append(el('p',k,'eyebrow'),el('h2',t),el('p',desc,'muted'));}
function download(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type}));let a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function snapshot(label){state.checkpoints.push({label,time:new Date().toISOString(),answers:{...state.answers},spec:state.spec});state.checkpoints=state.checkpoints.slice(-12);persist();note('Checkpoint saved in project data. Export for a durable backup.');}
function changed(){state.approved=false;state.spec='';persist();}
function blocked(){return D.checks(state.answers).some(x=>x.level==='block');}
function render(){persist();$('#steps').replaceChildren(...steps.map((s,i)=>{let b=button(String(i+1).padStart(2,'0')+'  '+s,()=>{state.step=i;render();},state.step===i?'active':'');b.setAttribute('aria-current',state.step===i?'step':'false');return b;}));$('#progress').style.setProperty('--progress',((state.step+1)/7*100)+'%');$('#view').replaceChildren();$('#back').disabled=state.step===0;$('#next').disabled=state.step===6;$('#next').textContent=state.step===0?'Next question →':'Continue →';const v=$('#view'),a=state.answers;
if(state.step===0){let q=D.questions[state.question];heading(`DISCOVERY / ${state.question+1} OF ${D.questions.length}`,q[1],q[2]);let label=el('label',q[1]);label.htmlFor='answer';label.className='sr-only';let input=el('textarea');input.id='answer';input.value=a[q[0]]||'';input.placeholder=q[2];input.maxLength=20000;input.oninput=()=>{a[q[0]]=input.value;changed();};v.append(label,input);let row=el('div',undefined,'actions');row.append(button('← Previous question',()=>{state.question=Math.max(0,state.question-1);render();}),el('span',`${D.questions.filter(([k])=>a[k]?.trim()).length} / ${D.questions.length} answered`));v.append(row);const details=el('details');details.append(el('summary','Jump to a question / review answers'));D.questions.forEach(([k,title],i)=>details.append(button(`${a[k]?.trim()?'✓':'○'} ${title}`,()=>{state.question=i;render();})));v.append(details);}
if(state.step===1){heading('SIZING / TRANSPARENT HEURISTIC','Right-size the plan','Requirements, integrations, data, permissions and existing code determine draft depth.');let c=D.complexity(a);v.append(el('div',`${c.depth} · ${c.score} points · ${D.phases(a).length} proposed phases`,'metric'));for(let [label,value]of c.factors)v.append(el('p',`${label}: ${value}`,'card'));v.append(el('p',c.disclaimer,'muted'));}
if(state.step===2){heading('ARCHITECTURE / EDITABLE DRAFT','Make the specification yours','The draft is assembled from your answers. Edit architecture details here. Scope and acceptance changes belong in the interview so the devplan stays aligned.');if(blocked())v.append(el('p','Complete the interview before generating a design. Review & correct lists missing answers.','warning'));v.append(button(state.spec?'Regenerate from interview':'Generate specification',()=>{if(blocked()){note('Complete required answers first.');return;}if(state.spec&&!confirm('Replace your edited specification? A checkpoint will be saved.'))return;snapshot('Before design generation');state.spec=D.specification(a);state.approved=false;render();},'primary'));let t=el('textarea');t.id='spec';t.setAttribute('aria-label','Editable specification');t.className='document';t.value=state.spec;t.placeholder='Your specification will appear here.';t.oninput=()=>{state.spec=t.value;state.approved=false;persist();};v.append(t);}
if(state.step===3){heading('QUALITY GATE / HUMAN IN THE LOOP','Review, correct, then approve','These are structural checks, not a semantic AI review. Resolve contradictions and confirm feasibility yourself or use the agent-review prompt.');let issues=D.checks(a);if(!state.spec)issues.push({level:'block',text:'Generate a specification in Design draft.'});for(let x of issues)v.append(el('p',`${x.level==='block'?'BLOCKER':'REVIEW'} · ${x.text}`,x.level==='block'?'warning':'card'));if(!issues.length)v.append(el('p','Structural checks passed. Human/agent design review is still required.','card'));v.append(button('Download agent-review prompt',()=>download('review-prompt.md',`Review this draft for feasibility, contradictions, scope creep, security, missing acceptance criteria and testability. Ask focused follow-up questions before implementing. Return corrections and explicit unresolved decisions, not invented approvals. Check interview/spec requirement parity.\n\nINTERVIEW\n${JSON.stringify(a,null,2)}\n\nSPECIFICATION\n${state.spec||'Not generated'}`)));let label=el('label',undefined,'approval'),cb=el('input');cb.type='checkbox';cb.id='approve';cb.checked=state.approved;cb.disabled=issues.some(x=>x.level==='block');cb.onchange=()=>{state.approved=cb.checked;persist();};label.append(cb,document.createTextNode(' I reviewed this draft, verified requirement/acceptance alignment, and acknowledge any listed open decisions.'));v.append(label);}
if(state.step===4){heading('EXECUTION MAP / REQUIREMENT-LINKED','One phase, one verifiable gate','Each implementation phase links back to requirements, with explicit dependencies, tests and evidence. This is a planning scaffold—not invented file-level repository analysis.');for(let p of D.phases(a)){let box=el('article',undefined,'card');box.append(el('span',`${p.id} · depends on ${p.depends.join(', ')||'nothing'}`,'eyebrow'),el('h3',p.title),el('p',p.gate));let d=el('details');d.append(el('summary','Tasks and handoff'));let pre=el('pre',D.artifacts(a,state.spec)[`phase-${p.id}.md`]);d.append(pre);box.append(d);v.append(box);}}
if(state.step===5){heading('RECOVERY / PROJECT CHECKPOINTS','Keep the reasoning, not just the result','Checkpoints preserve interview and specification inside the exported project. They do not snapshot source code, deployments or the Orbit desktop.');v.append(button('Save checkpoint',()=>{snapshot('Manual checkpoint');render();},'primary'));for(let c of [...state.checkpoints].reverse()){let box=el('div',undefined,'card');box.append(el('p',`${c.label} · ${c.time}`),button('Restore draft',()=>{if(!confirm('Replace current interview and specification with this checkpoint?'))return;let restore={...c,answers:{...c.answers}};snapshot('Before restore');state.answers=restore.answers;state.spec=restore.spec;state.approved=false;render();}));v.append(box);}if(!state.checkpoints.length)v.append(el('p','No checkpoints yet.','muted'));}
if(state.step===6){heading('DELIVERY / STATELESS ARTIFACTS','Ready for the next agent','Download the packet, extract it into your project, and give handoff.md to your coding agent. The planner never launches development or changes your repository.');if(!state.approved||blocked()||!state.spec){v.append(el('p','Complete the interview, generate a specification, and approve the review before exporting the development packet. Project backup is always available.','warning'));return;}let files=D.artifacts(a,state.spec);let row=el('div',undefined,'actions');row.append(button('Download complete ZIP',()=>download('devplan.zip',zip(files),'application/zip'),'primary'),button('Download selected file',()=>download(selected,files[selected])),button('Copy starting prompt',async()=>{try{await navigator.clipboard.writeText(files['handoff.md']);note('Starting prompt copied.');}catch{selected='handoff.md';render();note('Clipboard unavailable in this sandbox. Select the prompt below or download it.');}}));v.append(row);let tabs=el('div',undefined,'tabs');for(let name of Object.keys(files))tabs.append(button(name,()=>{selected=name;render();},name===selected?'active':''));v.append(tabs);let t=el('textarea');t.readOnly=true;t.className='document';t.setAttribute('aria-label','Artifact preview');t.value=files[selected]||files['spec.md'];v.append(t);}}
// ZIP STORE format: portable archive with UTF-8 names and CRC32; no external dependencies.
function zip(files){let entries=[],offset=0;const enc=new TextEncoder();const crc=b=>{let c=0xffffffff;for(let x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;};let chunks=[],central=[];for(let [name,text]of Object.entries(files)){let n=enc.encode(name),b=enc.encode(text),sum=crc(b),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,sum,true);v.setUint32(18,b.length,true);v.setUint32(22,b.length,true);v.setUint16(26,n.length,true);h.set(n,30);let ch=new Uint8Array(46+n.length),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,sum,true);cv.setUint32(20,b.length,true);cv.setUint32(24,b.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);ch.set(n,46);chunks.push(h,b);central.push(ch);offset+=h.length+b.length;entries.push(name);}let size=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);return new Blob([...chunks,...central,end]);}
$('#next').onclick=()=>{if(state.step===0){let [k]=D.questions[state.question];if(!state.answers[k]?.trim()){note('Answer this question before continuing. Use None or Undecided when appropriate.');return;}if(state.question<D.questions.length-1)state.question++;else state.step=1;}else state.step=Math.min(6,state.step+1);note('');render();};$('#back').onclick=()=>{state.step=Math.max(0,state.step-1);render();};$('#save').onclick=()=>download('devplan-project.json',JSON.stringify(state,null,2),'application/json');$('#new').onclick=()=>{if(!confirm('Start a new project? Export your current project first if you want to keep it.'))return;state={version:1,answers:{},spec:'',step:0,question:0,approved:false,checkpoints:[]};render();};$('#import').onchange=async e=>{try{let f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Project exceeds 2 MB.');const raw=JSON.parse(await f.text());let imported=D.parseProject(raw);if(Array.isArray(raw.checkpoints))imported.checkpoints=raw.checkpoints.slice(-12).map(c=>{let p=D.parseProject({version:1,answers:c.answers,spec:c.spec});return {answers:p.answers,spec:p.spec,label:String(c.label).slice(0,100),time:String(c.time).slice(0,50)};});if(!confirm('Replace current draft with imported project?'))return;state=imported;render();note('Project imported. Review approval must be renewed.');}catch(err){note('Import failed: '+err.message);}finally{e.target.value='';}};render();
