"""Generate local, deterministic icon packs; no third-party images or fonts."""
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]
paths={
'folder':'M6 12H19L23 17H42V39H6Z M6 22H42',
'chat':'M7 9H41V33H23L13 41V33H7Z M14 18H34 M14 25H28',
' terminal':'M5 9H43V39H5Z M12 18L19 24L12 30 M24 30H35',
'browser':'M24 5A19 19 0 1 0 24 43A19 19 0 1 0 24 5 M5 24H43 M24 5C11 15 11 33 24 43 M24 5C37 15 37 33 24 43',
'document':'M10 5H29L38 14V43H10Z M29 5V14H38 M17 22H31 M17 29H31 M17 36H27',
'grid':'M7 7H41V41H7Z M7 18H41 M7 29H41 M19 7V41 M30 7V41',
'image':'M5 8H43V40H5Z M6 35L18 22L27 31L34 24L42 34 M31 14H35V18H31Z',
'key':'M17 7A10 10 0 1 0 17 27A10 10 0 1 0 17 7 M24 24L41 41 M33 33L38 28 M38 38L43 33',
'app':'M7 7H21V21H7Z M27 7H41V21H27Z M7 27H21V41H7Z M27 27H41V41H27Z'}
paths={k.strip():v for k,v in paths.items()}
# Each pack changes silhouette, stroke language and internal decoration as well as color.
packs={
 'nous':('#eeecff','#2622a8','astrolabe','1.4','round'),
'midnight':('#b9ceff','#152137','hex','1.7','round'),
'xp':('#184291','#ffce53','gloss','2.6','round'),
'classic':('#000080','#ffff80','pixel','2','miter'),
'paper':('#302b27','#faf3df','paper','1.4','round'),
'cyberpunk':('#67fff4','#361242','cut','2','miter'),
'aurora':('#e7ffff','#317e9a','glass','1.6','round'),
'phosphor':('#8fff9d','#06230d','crt','1.6','miter'),
'blueprint':('#d0edff','#174474','draft','1.2','miter'),
'pop':('#221529','#ffdf43','burst','3.5','round'),
'ocean':('#d6ffff','#126e92','port','2','round'),
'forest':('#e0f0b7','#31532a','leaf','2.2','round'),
'plum':('#ffd6f4','#713955','seal','1.8','round'),
'ember':('#ffd58a','#65351d','plate','2.8','miter')}
frames={
 'astrolabe':'<circle cx="24" cy="24" r="20"/><circle cx="24" cy="24" r="23" fill="none" stroke-dasharray="1 3"/><path d="M24 0V6M24 42V48M0 24H6M42 24H48" fill="none"/>',
'hex':'<path d="M24 1L45 12V36L24 47L3 36V12Z"/>',
'gloss':'<rect x="1" y="1" width="46" height="46" rx="10"/><path d="M6 6H42V20Q24 28 6 20Z" fill="white" opacity=".35"/>',
'pixel':'<path d="M3 1H43V5H47V43H43V47H3V43H1V5H3Z"/><path d="M4 43V4H43" fill="none" stroke="white" stroke-width="3"/>',
'paper':'<path d="M3 1H37L47 11V47H3Z"/><path d="M37 1V11H47" fill="none"/>',
'cut':'<path d="M12 1H47V35L35 47H1V13Z"/><path d="M3 11H12V2 M36 46V36H46" fill="none"/>',
'glass':'<rect x="1" y="1" width="46" height="46" rx="16"/><ellipse cx="24" cy="10" rx="17" ry="6" fill="white" opacity=".25"/>',
'crt':'<rect x="1" y="1" width="46" height="46" rx="4"/><path d="M2 12H46M2 24H46M2 36H46" stroke="currentColor" opacity=".3"/>',
'draft':'<path d="M4 4H44V44H4Z" fill="none" stroke-dasharray="3 2"/><path d="M0 7H48M7 0V48M41 0V48M0 41H48" fill="none" opacity=".4"/>',
'burst':'<path d="M24 0L30 7L41 3L41 15L48 24L41 30L45 43L32 41L24 48L17 41L3 45L7 31L0 24L7 17L3 3L17 7Z"/>',
'port':'<circle cx="24" cy="24" r="23"/><circle cx="24" cy="24" r="20" fill="none" stroke-dasharray="2 5"/>',
'leaf':'<path d="M1 26Q1 0 47 1Q49 47 24 47Q1 47 1 26Z"/>',
'seal':'<path d="M24 1L30 5L38 4L40 12L47 17L43 25L46 33L39 38L35 46L25 43L17 47L12 40L4 37L5 28L1 20L7 14L10 5L18 5Z"/>',
'plate':'<rect x="1" y="1" width="46" height="46" rx="3"/><path d="M5 5H8M40 5H43M5 43H8M40 43H43" stroke-width="2"/>'}
css=['/* Generated by scripts/build_theme_icons.py. */', '.theme-icon{display:inline-grid;place-items:center;flex-shrink:0;width:24px;height:24px;vertical-align:middle;background:transparent;box-shadow:none}.theme-icon::before{content:"";display:block;width:100%;height:100%;background:var(--icon-image) center/contain no-repeat}.start-quick button{display:flex;align-items:center;gap:6px}.desktop-shortcut .theme-icon{width:44px;height:44px;background:transparent;box-shadow:none;border-radius:0}.start-button .theme-icon::after{content:none}']
for theme,(fg,bg,frame,weight,join) in packs.items():
 directory=R/'public'/'icons'/theme;directory.mkdir(parents=True,exist_ok=True)
 for role,path in paths.items():
  transform='translate(6 6) scale(.75)'
  if theme=='classic':transform='translate(4 4) scale(.83)'
  if theme=='paper':transform='translate(7 5) rotate(-4 24 24) scale(.72)'
  if theme=='cyberpunk':transform='translate(8 6) skewX(-8) scale(.76)'
  svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" color="{fg}" fill="{bg}" stroke="{fg}" stroke-width="1">{frames[frame]}<g transform="{transform}" fill="none" stroke="{fg}" stroke-width="{weight}" stroke-linejoin="{join}" stroke-linecap="{("square" if join=="miter" else "round")}"><path d="{path}"/></g></svg>'
  (directory/(role+'.svg')).write_text(svg)
  selector=f'html[data-orbit-style="{theme}"]'
  css.append(f'{selector} [data-icon="{role}"]{{--icon-image:url("/icons/{theme}/{role}.svg")}}')
# Safe fallback also covers unthemed workspaces.
for role in paths:css.append(f'html:not([data-orbit-style]),html[data-orbit-style=""]{{--unused:0}} .theme-icon[data-icon="{role}"]{{--icon-fallback:url("/icons/midnight/{role}.svg")}}')
css.append('.theme-icon::before{background-image:var(--icon-image,var(--icon-fallback))}')
(R/'src'/'theme-icons.css').write_text('\n'.join(css)+'\n')
print(f'Generated {len(packs)} packs, {len(paths)} semantic icons each')
