'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('dock-session')||'',busy=false;
function status(t){$('status').textContent=t;}
function locked(){token='';sessionStorage.removeItem('dock-session');$('pair').hidden=false;$('dock').hidden=true;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{'Authorization':'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok){if(r.status===401)locked();throw Error(d.error||'Request failed');}return d;}
function button(text,fn){const b=document.createElement('button');b.textContent=text;b.disabled=busy;b.onclick=()=>run(fn);return b;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function row(text){const d=document.createElement('div');d.className='row';const s=document.createElement('span');s.textContent=text;d.append(s);return d;}
async function refresh(){const d=await api('/api/state');$('pair').hidden=true;$('dock').hidden=false;$('windows').replaceChildren();for(const w of d.windows){const r=row(w.title);r.append(button('Focus',async()=>{const x=await api('/api/action',{action:'focus',id:w.id});status('Window '+x.result.status);await refresh();}));$('windows').append(r);}$('files').replaceChildren();for(const f of d.files){const r=row(f.name+' · '+f.size+' bytes');r.append(button('Read / retrieve',async()=>{const x=await api('/api/action',{action:'read',name:f.name});const bytes=Uint8Array.from(atob(x.result.data),c=>c.charCodeAt(0));if(/\.(txt|md|csv|json|log)$/i.test(f.name)){$('preview').textContent=new TextDecoder().decode(bytes);$('preview').hidden=false;}if(window.self===window.top){const u=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);status('File retrieved');}else status('Retrieved '+f.name+'. Text appears below; for downloads open the Dock address in a separate browser tab.');}));$('files').append(r);}$('events').replaceChildren(...d.events.map(e=>row(e.time+' · '+e.action+' · '+e.status+' · '+e.id)));}
$('connect').onclick=()=>run(async()=>{const d=await api('/api/pair',{code:$('code').value.trim()});token=d.token;sessionStorage.setItem('dock-session',token);$('code').value='';await refresh();status('Paired · live desktop connection');});
$('disconnect').onclick=()=>run(async()=>{if(!confirm('Revoke ALL Dock sessions and rotate the desktop pairing code? Running desktop apps will remain open.'))return;await api('/api/disconnect',{});locked();status('Disconnected all sessions. Reopen the pairing file to connect again.');});
$('refresh').onclick=()=>run(async()=>{await refresh();status('Desktop state refreshed');});
for(const [id,label] of Object.entries({files:'Inbox folder',editor:'Text editor',writer:'Writer',calc:'Calc',impress:'Impress'}))$('apps').append(button(label,async()=>{const d=await api('/api/action',{action:'launch',app:id});await refresh();status(label+': '+d.result.status);}));
async function upload(name,bytes){if(bytes.length>8*1024*1024)throw Error('Maximum file size is 8 MiB');let s='';for(let i=0;i<bytes.length;i+=16384)s+=String.fromCharCode(...bytes.subarray(i,i+16384));await api('/api/action',{action:'upload',name,data:btoa(s)});await refresh();status('Saved to desktop: '+name);}
$('upload').onchange=()=>run(async()=>{const f=$('upload').files[0];if(f){if(f.size>8*1024*1024)throw Error('Maximum file size is 8 MiB');await upload(f.name,new Uint8Array(await f.arrayBuffer()));$('upload').value='';}});
$('sendnote').onclick=()=>run(async()=>{if(!$('note').value.trim())throw Error('Enter some text first');await upload('Orbit-note-'+Date.now()+'.txt',new TextEncoder().encode($('note').value));$('note').value='';});
if(token)run(async()=>{await refresh();status('Paired · live desktop connection');});
setInterval(()=>{if(token&&!busy&&!document.hidden)run(refresh);},8000);
