const $=id=>document.getElementById(id),K=window.latticeSDK,I=window.sourceIndex,base=window.latticeBase||'https://kimi.tailec998.ts.net:10448';
let state=K.create(),selected='front-0',engine=null,draft=null,previewDigest='',busy=false;
const json=v=>JSON.stringify(v,null,2),text=(id,v)=>$(id).textContent=typeof v==='string'?v:json(v);
function tab(id){for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==id;for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.tab===id);}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
text('revision',I.branch+'\n'+I.commit.slice(0,12));$('captureSource').href='https://github.com/mojomast/cocs/blob/'+I.commit+'/game/cocs.mjs#L533';
function metrics(id,values){$(id).replaceChildren();for(const [label,value]of values){const div=document.createElement('div');div.className='metric';const b=document.createElement('b'),s=document.createElement('span');b.textContent=value;s.textContent=label;div.append(b,s);$(id).append(div);}}
const NS='http://www.w3.org/2000/svg';function svg(tag,attrs,textValue){const el=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(textValue!==undefined)el.textContent=textValue;return el;}
function render(){K.updateLiveNodes(state);const info=K.inspect(state),nodes=state.nodes,xy=n=>[480+n.x*3.5,215+n.z*5];$('graph').replaceChildren();
 for(const edge of state.edges){const a=nodes.find(n=>n.id===(edge.a??edge[0])),b=nodes.find(n=>n.id===(edge.b??edge[1]));if(!a||!b)continue;const [x1,y1]=xy(a),[x2,y2]=xy(b),cut=state.cuts.includes(a.id)||state.cuts.includes(b.id);$('graph').append(svg('line',{x1,y1,x2,y2,stroke:cut?'#e77b8c':a.owner!==null&&a.owner===b.owner?'#81bdb0':'#455a73','stroke-width':cut?4:2,'stroke-dasharray':cut?'6 5':'none'}));}
 for(const n of nodes){const [x,y]=xy(n),g=svg('g',{tabindex:0,role:'button','aria-label':n.id});g.append(svg('circle',{cx:x,cy:y,r:n.id===selected?25:20,fill:n.owner===0?'#207e89':n.owner===1?'#b14561':'#4a5360',stroke:n.id===selected?'#cafa7a':'#8ba6be','stroke-width':n.id===selected?4:1}),svg('text',{x,y:y+44,'text-anchor':'middle'},n.id),svg('text',{x,y:y+5,'text-anchor':'middle'},state.cuts.includes(n.id)?'×':n.archetype==='hq'?'HQ':n.owner??'·'));g.onclick=()=>{selected=n.id;render();};g.onkeydown=e=>{if(e.key==='Enter'){selected=n.id;render();}};$('graph').append(g);}
 const n=nodes.find(n=>n.id===selected)||nodes[0];selected=n.id;text('nodeTitle',n.id+' · '+n.archetype);$('owner').value=n.owner===null?'':String(n.owner);text('node',{...info.nodes.find(x=>x.id===n.id),progress:n.progress,captureSeconds:state.captureSeconds});metrics('income',[['Team 0 connected node FLUX/s',info.income[0]],['Team 1 connected node FLUX/s',info.income[1]],['Passive FLUX/s (before neglect)',state.fluxPassive],['Majority needed',state.dominanceCount]]);}
$('owner').onchange=()=>{state.nodes.find(n=>n.id===selected).owner=$('owner').value===''?null:Number($('owner').value);render();};$('cut').onclick=()=>{K.cutLink(state,selected);render();};$('repair').onclick=()=>{K.repairLink(state,selected);render();};$('reset').onclick=()=>{state=K.create($('mode').value);render();};$('mode').onchange=$('reset').onclick;$('endgame').onclick=()=>{K.enterEndgame(state);render();};
$('captureScenario').onclick=()=>{state=K.create($('mode').value);for(const n of state.nodes)if(['front-0','econ-n','relay-0'].includes(n.id))n.owner=0;render();};$('cutScenario').onclick=()=>{$('captureScenario').click();K.cutLink(state,'front-0');selected='front-0';render();};
function director(){const seconds=Number($('seconds').value),d=K.director($('tier').value,Number($('wave').value),seconds);text('secondsValue',seconds+' s');metrics('directorMetrics',[['Pacing phase',d.phase],['Pressure / second',d.rate],['Pressure cap',d.cap],['Budget probe',d.pressure.toFixed(1)]]);text('wavePlan',d.plan);text('sinks',K.COOP_SINKS);text('req',K.REQ_ITEMS);text('score',K.scoreEvent({kind:$('event').value,archetype:'front',deniedNodes:Number($('amount').value),seconds:Number($('amount').value)}));}
for(const id of ['tier','wave','seconds','event','amount'])$(id).oninput=director;
const flows=[['core.mjs','Match.step → actor loop → objective update'],['objectives.mjs','Objective dispatch → stepCocs'],['cocs.mjs','Lattice capture → HQ connectivity → orders → snapshot'],['cocs-economy.mjs','Objective score / FLUX / personal REQ / neglect'],['cocs-coop.mjs','Operations wave lifecycle / spend window / HQ siege'],['cocs-director.mjs','Pure Director planner / pacing / spawn selection'],['cocs-terminals.mjs','Terminal state / interaction channels'],['cocs-traversal.mjs','Devices / cut-lock-repair / vehicle depots'],['lattice-support.mjs','Operator and harness objective effects'],['protocol.mjs','Snapshot delta encoding / replication']];
for(const [name,label]of flows){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{showModule('game/'+name);};$('flow').append(b);}
function showModule(path,line=1){const m=I.modules.find(m=>m.path===path);if(!m)return;$('module').value=path;$('sourceLink').href=m.url+'#L'+line;const src=$('source');src.replaceChildren();m.source.split('\n').forEach((t,i)=>{const span=document.createElement('span');span.className='line'+(i+1===line?' highlight':'');span.textContent=String(i+1).padStart(4)+'  '+t;src.append(span);});src.scrollTop=Math.max(0,(line-4)*18);for(const id of ['imports','symbols'])$(id).replaceChildren();for(const p of m.imports){const b=document.createElement('button');b.textContent=p;b.disabled=!I.modules.some(x=>x.path===p);b.onclick=()=>showModule(p);$('imports').append(b);}for(const x of m.exports){const b=document.createElement('button');b.textContent=x.name+':'+x.line;b.onclick=()=>showModule(path,x.line);$('symbols').append(b);}}
function search(){const q=$('search').value.toLowerCase(),modules=I.modules.filter(m=>(m.path+' '+m.source).toLowerCase().includes(q));$('module').replaceChildren(...modules.map(m=>new Option(m.path,m.path)));if(modules[0]){const lines=modules[0].source.split('\n');showModule(modules[0].path,q?Math.max(1,lines.findIndex(l=>l.toLowerCase().includes(q))+1):1);}else{text('source','No matching source modules.');$('symbols').replaceChildren();$('imports').replaceChildren();}}
$('search').oninput=search;$('module').onchange=()=>showModule($('module').value);
function engineRender(){text('engineStatus',`Mode ${engine.config?.mode||$('mode').value} · ${engine.time.toFixed(3)} seconds · ${engine.actors.length} actors`);text('engineState',K.cocsSnapshot(engine));}
$('engineReset').onclick=()=>{try{engine=K.match($('mode').value,$('tier').value);engineRender();}catch(e){text('engineStatus',e.message);}};
$('step').onclick=()=>{try{if(!engine)$('engineReset').click();for(let i=0;i<60;i++)engine.step(1/60);engineRender();}catch(e){text('engineStatus',e.message);}};
$('place').onclick=()=>{if(!engine)$('engineReset').click();const n=engine.objectiveState.nodes.find(n=>n.id===selected),a=engine.actors[0];if(n&&a){a.x=n.x;a.y=n.y;a.z=n.z;a.health=100;engineRender();}};
function scenario(){return {schema:'cocs.scenario/v1',source:{commit:I.commit,branch:I.branch},mode:$('mode').value,tier:$('tier').value,wave:Number($('wave').value),seconds:Number($('seconds').value),selected,owners:state.nodes.map(n=>({id:n.id,owner:n.owner})),cuts:[...state.cuts],endgame:state.endgame};}
function brief(){return {schema:'cocs.change-brief/v1',scenario:scenario(),system:$('system').value,module:$('module').value,request:$('prompt').value};}
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([json(brief())],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='cocs-lattice-change-brief.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
async function api(op,data={}){if(window.draftOnly)throw Error('Read-only draft preview. Return to the parent lab to publish.');const r=await fetch(base+'/api',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json','X-Workshop-Token':window.workshopToken},body:JSON.stringify({op,...data})}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function buttons(){const ready=draft?.status==='ready';$('generate').disabled=busy||window.draftOnly;$('refine').disabled=busy||!ready;$('preview').disabled=busy||!['ready','published'].includes(draft?.status);$('revalidate').disabled=busy||!['ready','blocked'].includes(draft?.status);$('pr').disabled=busy||!ready||previewDigest!==draft.digest||!$('approved').checked;$('stop').disabled=!['running','queued','waiting_for_approval'].includes(draft?.status);$('approval').hidden=draft?.status!=='waiting_for_approval';}
function renderDraft(s){draft=s;text('status',s.status+(s.error?'\n'+s.error:''));text('output',s.output||'');text('evidence',(s.files||[]).join('\n')+'\n'+(s.evidence||''));text('diff',s.diff||'');$('prLink').replaceChildren();if(/^https:\/\/github\.com\/mojomast\/cocs\/pull\/\d+$/.test(s.pr||'')){const a=document.createElement('a');a.href=s.pr;a.textContent='Open pull request';a.target='_blank';a.rel='noopener';$('prLink').append(a);}buttons();}
const error=e=>text('status',e.message);
async function history(){const rows=await api('list');$('history').replaceChildren(new Option('Saved drafts…',''),...rows.map(s=>new Option(s.asset+' · '+s.status+' · '+s.id.slice(0,6),s.id)));}
async function edit(refine){if(!$('prompt').value.trim())return error(Error('Enter a requested change.'));busy=true;previewDigest='';$('approved').checked=false;buttons();try{renderDraft(await api('edit',{asset:refine?draft.asset:'operation:'+$('system').value,prompt:json(brief()),...(refine?{id:draft.id}:{})}));await history();}catch(e){error(e);}finally{busy=false;buttons();}}
$('generate').onclick=()=>edit(false);$('refine').onclick=()=>edit(true);$('history').onchange=async()=>{if(!$('history').value)return;previewDigest='';$('approved').checked=false;try{renderDraft(await api('get',{id:$('history').value}));}catch(e){error(e);}};
$('preview').onclick=async()=>{try{const d=await api('preview',{id:draft.id});$('draftPreview').srcdoc=d.html;$('draftPreview').hidden=false;previewDigest=d.digest;buttons();}catch(e){error(e);}};
$('revalidate').onclick=async()=>{busy=true;previewDigest='';$('approved').checked=false;buttons();try{renderDraft(await api('revalidate',{id:draft.id}));}catch(e){error(e);}finally{busy=false;buttons();}};
$('approved').onchange=buttons;$('pr').onclick=()=>{if(!$('title').value.trim())return error(Error('Enter a PR title.'));text('summary',$('title').value+'\nTarget: feat/fieldwork-plan\n'+draft.files.join('\n'));$('confirm').showModal();};$('cancel').onclick=()=>$('confirm').close();
$('publish').onclick=async()=>{$('confirm').close();busy=true;buttons();try{renderDraft(await api('publish',{id:draft.id,digest:previewDigest,confirm:true,title:$('title').value}));}catch(e){error(e);}finally{busy=false;buttons();}};
$('stop').onclick=async()=>{try{await api('stop',{id:draft.id});}catch(e){error(e);}};$('approval').onclick=async()=>{try{text('tools',await api('approvals',{id:draft.id}));$('toolDialog').showModal();}catch(e){error(e);}};for(const [id,choice]of [['allow','once'],['deny','deny']])$(id).onclick=async()=>{try{await api('approval',{id:draft.id,choice});$('toolDialog').close();}catch(e){error(e);}};$('closeTools').onclick=()=>$('toolDialog').close();
setInterval(async()=>{if(!draft||busy||['ready','blocked','published','publish-review'].includes(draft.status))return;try{renderDraft(await api('get',{id:draft.id}));}catch(e){error(e);}},3000);
render();director();search();buttons();if(!window.draftOnly)history().catch(error);else{document.querySelector('[data-tab=change]').hidden=true;text('revision','READ-ONLY DRAFT · '+I.commit.slice(0,12));}window.lab={scenario,brief,get state(){return state;}};
