import { el, button } from './dom';
import { workspaceId, ensureWorkspaceSynced } from './workspace-sync';
import type { PluginInstance } from './plugins';
export function showPlugins(token:()=>string){
 const dialog=el('dialog','hermes-tools-dialog');dialog.setAttribute('aria-label','Workspace plugins');const status=el('p'),list=el('div');let revision=0,busy=false;
 async function api(body:Record<string,unknown>){const r=await fetch('/api/workspace',{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceId,...body})});const data=await r.json();if(!r.ok)throw Error(data.error||'Plugin request failed');return data;}
 async function change(operations:Record<string,unknown>[]){if(busy)return;busy=true;try{await api({action:'plugins_apply',base_revision:revision,operations});status.textContent='Saved. Connected workspace will update automatically.';await load();}catch(e){status.textContent=String(e);}finally{busy=false;}}
 async function load(){try{await ensureWorkspaceSynced();const data=await api({action:'read'});revision=data.revision;list.replaceChildren();for(const p of (data.state.plugins||[]) as PluginInstance[]){const active=data.state.monitors.some((m:any)=>m.id===p.window.id);const row=el('section');row.append(el('h3','',`${p.manifest.title} · ${p.manifest.version}`),el('p','',`${p.manifest.id} · ${active?'Enabled':'Disabled'} · sandboxed app`),button(active?'Disable':'Enable',`${active?'Disable':'Enable'} plugin ${p.manifest.id}`,()=>{void change([{action:active?'plugin_disable':'plugin_enable',plugin_id:p.manifest.id}]);}),button('Configure',`Configure plugin ${p.manifest.id}`,()=>{const text=window.prompt('Plugin configuration (JSON object; no secrets)',JSON.stringify(p.config));if(text===null)return;try{void change([{action:'plugin_configure',plugin_id:p.manifest.id,config:JSON.parse(text)}]);}catch(e){status.textContent=String(e);}}),button('Remove',`Remove plugin ${p.manifest.id}`,()=>{if(window.confirm('Remove plugin from this workspace? A checkpoint is saved; published files are retained.'))void change([{action:'plugin_remove',plugin_id:p.manifest.id}]);}));list.append(row);}if(!list.children.length)list.textContent='No plugins installed. Install a local manifest below, or ask Hermes to publish and install one.';}catch(e){status.textContent=String(e);}}
 const input=el('textarea');input.setAttribute('aria-label','Plugin manifest JSON');input.placeholder='{"apiVersion":1,"id":"my-widget","version":"1.0.0","title":"My widget","entry":"/apps/my-widget-v1/index.html"}';
 dialog.append(el('h2','','Workspace plugins'),el('p','','Sandboxed app modules. Configuration and lifecycle changes are checkpointed. Plugins receive no host credentials. Published apps may access the network.'),button('Close','Close workspace plugins',()=>dialog.close()),button('Refresh','Refresh workspace plugins',()=>{void load();}),button('Disable all plugins','Disable all workspace plugins',()=>{if(window.confirm('Disable all plugin windows? Core chat and terminals remain.'))void change([{action:'plugin_disable_all'}]);}),list,input,button('Install disabled','Install plugin manifest',()=>{try{void change([{action:'plugin_install',manifest:JSON.parse(input.value)}]);}catch(e){status.textContent=String(e);}}),status);
 dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();void load();
}
