import { el, button } from './dom';
import { workspaceId, ensureWorkspaceSynced } from './workspace-sync';
export function showHistory(token:()=>string){
 const d=el('dialog','hermes-tools-dialog');d.setAttribute('aria-label','Workspace checkpoints');const status=el('p');const list=el('div');let revision=0;
 async function api(body:Record<string,unknown>){const r=await fetch('/api/workspace',{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceId,...body})});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
 async function load(){try{await ensureWorkspaceSynced();const data=await api({action:'history'});revision=data.revision;list.replaceChildren();for(const c of data.checkpoints){list.append(button(`${c.label} · ${new Date(c.created).toLocaleString()}`,`Restore checkpoint ${c.id}`,async()=>{if(!window.confirm('Restore layout? Removed panes may disconnect terminals. Theme files, apps, messages, shell effects and external actions are NOT restored. A before-restore checkpoint will be saved.'))return;try{await api({action:'restore',checkpoint_id:c.id,base_revision:revision,confirm:true});status.textContent='Layout restored; connected workspace will synchronize.';await load();}catch(e){status.textContent=String(e);}}));}if(!data.checkpoints.length)list.textContent='No checkpoints yet.';}catch(e){status.textContent=String(e);}}
 d.append(el('h2','','Workspace checkpoints'),el('p','','Layout and structured appearance recovery: saved windows, panes, geometry, text sizes and background settings. Does not snapshot CSS files, image bytes, plugin assets, conversations or live processes.'),button('Close','Close workspace checkpoints',()=>d.close()),button('Save checkpoint','Save workspace checkpoint',async()=>{try{await ensureWorkspaceSynced();await api({action:'checkpoint',label:'Manual checkpoint'});await load();}catch(e){status.textContent=String(e);}}),button('Refresh','Refresh workspace checkpoints',()=>{void load();}),status,list);
 d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();void load();
}
