import {button,el} from './dom';
import {validChat} from './chat-storage';
type Data=Record<string,any>;
export function mountWorkbenchTaskAuthority(args:{container:HTMLElement;token:()=>string;workspace_id:string;project_id:string}){
  let disposed=false,busy=false,grantId='',nativePreview:Data|null=null,environmentPreview:Data|null=null,profileId='';
  const status=el('p','','Task authority: loading…'),candidates=el('select'),recipients=el('select'),contexts=el('select'),attempts=el('select'),detail=el('pre');
  candidates.setAttribute('aria-label','Authority candidate');recipients.setAttribute('aria-label','Native agent recipient');contexts.setAttribute('aria-label','Native approved context packet');attempts.setAttribute('aria-label','Native task attempt');
  const budgetCalls=el('input'),budgetChecks=el('input'),budgetSeconds=el('input');
  for(const input of [budgetCalls,budgetChecks,budgetSeconds])input.type='number';budgetCalls.value='20';budgetChecks.value='3';budgetSeconds.value='180';
  budgetCalls.setAttribute('aria-label','Tool call budget');budgetChecks.setAttribute('aria-label','Managed check budget');budgetSeconds.setAttribute('aria-label','Attempt duration seconds');
  let state:Data={};
  let acceptancePreview:Data|null=null;
  const requireNode=el('input'),requireHost=el('input');requireNode.type='checkbox';requireHost.type='checkbox';requireNode.checked=true;
  requireNode.setAttribute('aria-label','Require Node test suite');requireHost.setAttribute('aria-label','Require host-owned sum regression fixture');
  const grants=el('select');grants.setAttribute('aria-label','Native consent record');
  let unknownDigest='';
  grants.addEventListener('change',()=>{grantId=grants.value;unknownDigest='';});
  const row=(label:string,node:HTMLElement)=>{const wrapper=el('label','',label);wrapper.append(node);return wrapper;};
  async function api(endpoint:string,body:Data){const response=await fetch(`/api/workbench/${endpoint}`,{method:'POST',headers:{Authorization:`Bearer ${args.token()}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:args.workspace_id,project_id:args.project_id,...body})});const data=await response.json();if(!response.ok||data.ok!==true)throw Error(data.code??'unavailable');return data;}
  async function act(label:string,work:()=>Promise<void>,intervention=false){if(disposed||busy&&!intervention)return;if(!intervention)busy=true;status.textContent=label;try{await work();if(!disposed)status.textContent=`${label}: complete. Refresh status to inspect current records.`;}catch(error){if(!disposed)status.textContent=`${label}: ${error instanceof Error?error.message:'unavailable'}. No automatic execution retry.`;}finally{if(!intervention)busy=false;}}
  function choices(select:HTMLSelectElement,values:{id:string;label:string}[]){const old=select.value;select.replaceChildren();for(const value of values){const option=el('option','',value.label);option.value=value.id;select.append(option);}if(values.some(v=>v.id===old))select.value=old;}
  async function refresh(){await act('Loading task authority',async()=>{
    const [execution,context]=await Promise.all([api('execution',{action:'execution_state'}),api('context',{action:'list'})]);if(disposed)return;state=execution;
    choices(candidates,(execution.candidates??[]).map((c:Data)=>({id:c.id,label:`${c.id} · generation ${c.generation}`})));
    choices(attempts,(context.attempts??[]).map((a:Data)=>({id:a.id,label:`${a.id} · ${a.task_id}`})));
    choices(contexts,[{id:'',label:'No context read grant'},...(context.contexts??[]).filter((c:Data)=>c.source?.kind==='packet').map((c:Data)=>({id:c.id,label:`Packet ${c.id} · ${c.snapshot?.bytes} bytes · ${c.snapshot?.hash}`}))]);
    const native=await api('native',{action:'list'});if(disposed)return;choices(grants,(native.grants??[]).map((g:Data)=>({id:g.id,label:`${g.id} · ${g.status}`})));grantId=grants.value;
    const response=await fetch('/api/workbench',{method:'POST',headers:{Authorization:`Bearer ${args.token()}`,'Content-Type':'application/json'},body:JSON.stringify({action:'list',workspace_id:args.workspace_id})});const list=await response.json();if(disposed)return;
    const values=[];for(const pane of list.surfaces??[]){if(pane.kind!=='agent')continue;try{const saved=JSON.parse(sessionStorage.getItem(`orbit-hermes-chat:${pane.pane_id}`)||'null');if(validChat(saved))values.push({id:JSON.stringify({pane_id:pane.pane_id,profile_id:saved.profile_id??'default',session_id:saved.session}),label:`${pane.name} · ${saved.profile_id??'default'} · ${saved.session}`});}catch{}}
    choices(recipients,values);
  });}
  const bind=button('Create bound attempt','Bind selected candidate to the selected agent conversation',()=>void act('Creating bound attempt',async()=>{const candidate=(state.candidates??[]).find((c:Data)=>c.id===candidates.value);if(!candidate||!recipients.value)throw Error('Choose a candidate and bound agent conversation');const result=await api('execution',{action:'attempt_create',candidate_id:candidate.id,task_id:candidate.task_id,...JSON.parse(recipients.value)});choices(attempts,[{id:result.attempt.id,label:result.attempt.id}]);detail.textContent=JSON.stringify(result,null,2);}));
  const previewNative=button('Preview native task consent','Preview candidate read/edit and approved check authority',()=>void act('Previewing native task consent',async()=>{nativePreview=await api('native',{action:'preview',attempt_id:attempts.value,context_ids:contexts.value?[contexts.value]:[],budget:{calls:budgetCalls.valueAsNumber,checks:budgetChecks.valueAsNumber,duration_ms:budgetSeconds.valueAsNumber*1000}});detail.textContent=JSON.stringify(nativePreview,null,2);}));
  const approveNative=button('Approve native task consent','Approve exactly the previewed bounded task authority',()=>void act('Approving native task consent',async()=>{if(!nativePreview)throw Error('Preview task consent first');const result=await api('native',{action:'approve',preview_id:nativePreview.preview_id,preview_digest:nativePreview.preview_digest});grantId=result.grant.id;nativePreview=null;detail.textContent=JSON.stringify(result,null,2);}));
  const start=button('Start native Hermes attempt','Start Hermes with only the approved Workbench tools',()=>void act('Starting native Hermes',async()=>{const result=await api('native',{action:'start',grant_id:grantId});detail.textContent=JSON.stringify(result,null,2);}));
  const check=button('Read native attempt status','Read status without retrying execution',()=>void act('Reading native status',async()=>{const result=await api('native',{action:'status',grant_id:grantId});unknownDigest=result.unknown_digest??'';detail.textContent=JSON.stringify(result,null,2);},true));
  const stop=button('Stop native attempt','Revoke native tools and request agent stop; jobs require separate cancellation',()=>void act('Stopping native attempt',async()=>{detail.textContent=JSON.stringify(await api('native',{action:'stop',grant_id:grantId}),null,2);},true));
  const previewEnv=button('Preview offline Node environment','Preview lockfile, tarball inputs and scripts-disabled offline preparation',()=>void act('Previewing environment',async()=>{const c=(state.candidates??[]).find((c:Data)=>c.id===candidates.value);if(!c)throw Error('Choose a candidate');environmentPreview=await api('environments',{action:'profile_preview',candidate_id:c.id,required_inputs:c.files.filter((f:Data)=>['package.json','package-lock.json'].includes(f.path)||f.path.endsWith('.tgz')).map((f:Data)=>f.path)});detail.textContent=JSON.stringify(environmentPreview,null,2);}));
  const approveEnv=button('Approve offline Node environment','Approve exactly the previewed dependency preparation',()=>void act('Approving environment',async()=>{if(!environmentPreview)throw Error('Preview environment first');const result=await api('environments',{action:'profile_approve',preview_id:environmentPreview.preview_id,preview_digest:environmentPreview.preview_digest});profileId=result.id;detail.textContent=JSON.stringify(result,null,2);}));
  const prepare=button('Prepare locked dependencies','Run only the approved offline npm ci with lifecycle scripts disabled',()=>void act('Preparing dependencies',async()=>{detail.textContent=JSON.stringify(await api('environments',{action:'environment_prepare',profile_id:profileId}),null,2);}));
  const previewAcceptance=button('Preview required checks','Preview the entire required check set and prepared environment binding',()=>void act('Previewing acceptance revision',async()=>{const execution=await api('execution',{action:'execution_state'}),candidate=execution.candidates.find((c:Data)=>c.id===candidates.value),task=execution.tasks.find((t:Data)=>t.id===candidate?.task_id);if(!task)throw Error('Choose a candidate');const required_checks=[];if(requireNode.checked)required_checks.push({definition_id:'node-test',...(profileId?{execution_profile_id:profileId}:{})});if(requireHost.checked)required_checks.push({definition_id:'host-regression'});acceptancePreview=await api('execution',{action:'task_acceptance_preview',candidate_id:candidate.id,task_id:task.id,expected_acceptance_digest:task.acceptance_digest,required_checks});detail.textContent=JSON.stringify(acceptancePreview,null,2);}));
  const approveAcceptance=button('Approve required checks','Approve exactly the previewed full acceptance contract; historical evidence becomes stale',()=>void act('Approving acceptance revision',async()=>{if(!acceptancePreview)throw Error('Preview the complete check set first');const p=acceptancePreview.preview;detail.textContent=JSON.stringify(await api('execution',{action:'task_acceptance_approve',candidate_id:candidates.value,task_id:p.task_id,preview_id:acceptancePreview.preview_id,preview_digest:p.digest??p.preview_digest??acceptancePreview.preview_digest}),null,2);acceptancePreview=null;nativePreview=null;}));
  args.container.replaceChildren(el('h3','','Task authority and execution environment'),status,row('Candidate',candidates),row('Agent conversation',recipients),bind,row('Attempt',attempts),row('Packet',contexts),el('p','','Create the bound attempt, then capture a question/context packet linked to it. Refresh here before granting reads. Dedicated Hermes is trusted-host execution, not a filesystem sandbox.'),row('Tool calls',budgetCalls),row('Checks',budgetChecks),row('Seconds',budgetSeconds),previewNative,approveNative,start,check,stop,previewEnv,approveEnv,prepare,button('Refresh task authority','Refresh task, packet and conversation metadata',()=>void refresh()),detail);
  const terminated=el('input');terminated.type='checkbox';terminated.setAttribute('aria-label','I independently confirmed the unknown native process has terminated');
  args.container.append(row('Native consent',grants),row('I independently confirmed the unknown native process has terminated',terminated),button('Acknowledge unknown native outcome','Release quarantine for this exact externally terminated run without replay',()=>void act('Acknowledging unknown outcome',async()=>{if(!terminated.checked||!unknownDigest)throw Error('Read the unknown status and independently confirm termination first');detail.textContent=JSON.stringify(await api('native',{action:'acknowledge_unknown',grant_id:grantId,expected_digest:unknownDigest,known_externally_terminated:true}),null,2);unknownDigest='';terminated.checked=false;},true)));
  args.container.append(el('h4','','Required checks'),row('Node test suite',requireNode),row('Host-owned sum regression fixture',requireHost),previewAcceptance,approveAcceptance);
  for(const select of [attempts,contexts,candidates,recipients])select.addEventListener('change',()=>{nativePreview=null;environmentPreview=null;});
  void refresh();return {refresh,dispose(){disposed=true;args.container.replaceChildren();}};
}
